Const $N_BTMASK = 0xF
Const $N_BTSHFT = 4
Const $N_TMASK = 0x30
Const $N_TMASK1 = 0xC0
Const $N_TMASK2 = 0xF0
Const $N_TSHIFT = 2
Const $NABTS_BYTES_PER_LINE = 36
Const $NABTS_LINES_PER_BUNDLE = 16
Const $NABTS_PAYLOAD_PER_LINE = 28
Const $NAL_CAPTURE_NOT_PAUSED = $BHERR_CAPTURE_NOT_PAUSED
Const $NAL_CAPTURE_NOT_STARTED = $BHERR_NOT_CAPTURING
Const $NAL_CAPTURE_PAUSED = $BHERR_CAPTURE_PAUSED
Const $NAL_CAPTURE_STARTED = $BHERR_CAPTURING
Const $NAL_INTERNAL_EXCEPTION = $BHERR_INTERNAL_EXCEPTION
Const $NAL_INVALID_HBUFFER = $BHERR_INVALID_HBUFFER
Const $NAL_INVALID_HNETCONTEXT = $BHERR_INVALID_HNETWORK
Const $NAL_INVALID_NETWORK_ID = $BHERR_INVALID_NETWORK_ID
Const $NAL_INVALID_PACKET_LENGTH = $BHERR_INVALID_PACKET_LENGTH
Const $NAL_MAC_DRIVER_OPEN_FAILURE = $BHERR_MAC_DRIVER_OPEN_FAILURE
Const $NAL_MSDOS_DRIVER_INIT_FAILURE = $BHERR_MSDOS_DRIVER_INIT_FAILURE
Const $NAL_MSDOS_DRIVER_NOT_LOADED = $BHERR_MSDOS_DRIVER_NOT_LOADED
Const $NAL_NETWORK_BUSY = $BHERR_NETWORK_BUSY
Const $NAL_OUT_OF_MEMORY = $BHERR_OUT_OF_MEMORY
Const $NAL_PENDING = $BHERR_PENDING
Const $NAL_PROMISCUOUS_MODE_NOT_SUPPORTED = $BHERR_PROMISCUOUS_MODE_NOT_SUPPORTED
Const $NAL_SUCCESS = $BHERR_SUCCESS
Const $NAL_TRANSMIT_ERROR = $BHERR_TRANSMIT_ERROR
Const $NAL_WINDOWS_DRIVER_INIT_FAILURE = $BHERR_WINDOWS_DRIVER_INIT_FAILURE
Const $NAL_WINDOWS_DRIVER_NOT_LOADED = $BHERR_WINDOWS_DRIVER_NOT_LOADED
Const $NAME_FLAGS_MASK = 0x87
Const $NAME_SIZE = 52
Const $NAMES_LOCALFORALL = 4
Const $NAMES_LOCALFORLOCAL = 2
Const $NAMES_LOCALFORNODE = 3
Const $NAMES_LOCALFORREMOTE = 1
Const $NAMES_MODEFORALL = 8
Const $NAMES_REMOTEFORALL = 7
Const $NAMES_REMOTEFORLOCAL = 5
Const $NAMES_REMOTEFORNODE = 6
Const $NAMESPACE_CLASS_NAME = "Namespace"
Const $NANOSECONDS = 10000000
Const $NAVDIR_DOWN = 0x2
Const $NAVDIR_FIRSTCHILD = 0x7
Const $NAVDIR_LASTCHILD = 0x8
Const $NAVDIR_LEFT = 0x3
Const $NAVDIR_MAX = 0x9
Const $NAVDIR_MIN = 0
Const $NAVDIR_NEXT = 0x5
Const $NAVDIR_PREVIOUS = 0x6
Const $NAVDIR_RIGHT = 0x4
Const $NAVDIR_UP = 0x1
Const $NCBACTION = 0x77
Const $NCBADDGRNAME = 0x36
Const $NCBADDNAME = 0x30
Const $NCBASTAT = 0x33
Const $NCBCALL = 0x10
Const $NCBCANCEL = 0x35
Const $NCBCHAINSEND = 0x17
Const $NCBCHAINSENDNA = 0x72
Const $NCBDELNAME = 0x31
Const $NCBDGRECV = 0x21
Const $NCBDGRECVBC = 0x23
Const $NCBDGSEND = 0x20
Const $NCBDGSENDBC = 0x22
Const $NCBENUM = 0x37
Const $NCBFINDNAME = 0x78
Const $NCBHANGUP = 0x12
Const $NCBLANSTALERT = 0x73
Const $NCBLISTEN = 0x11
Const $NCBNAMSZ = 16
Const $NCBRECV = 0x15
Const $NCBRECVANY = 0x16
Const $NCBRESET = 0x32
Const $NCBSEND = 0x14
Const $NCBSENDNA = 0x71
Const $NCBSSTAT = 0x34
Const $NCBTRACE = 0x79
Const $NCBUNLINK = 0x70
Const $NDDE_ACCESS_DENIED = 1
Const $NDDE_BUF_TOO_SMALL = 2
Const $NDDE_CANT_ACCESS_SERVER = 24
Const $NDDE_CMD_SHOW_MASK = 0xFFFF
Const $NDDE_ERROR_MORE_DATA = 3
Const $NDDE_GUI_CHANGE = BitOR($NDDE_SHARE_GENERIC_READ, $NDDE_SHARE_GENERIC_WRITE, $NDDE_SHARE_GENERIC_EXECUTE)
Const $NDDE_GUI_FULL_CONTROL = $NDDE_SHARE_GENERIC_ALL
Const $NDDE_GUI_NONE = 0
Const $NDDE_GUI_READ = $NDDE_SHARE_GENERIC_READ
Const $NDDE_GUI_READ_LINK = BitOR($NDDE_SHARE_GENERIC_READ, $NDDE_SHARE_INITIATE_LINK)
Const $NDDE_INTERNAL_ERROR = 11
Const $NDDE_INVALID_APPNAME = 13
Const $NDDE_INVALID_FILENAME = 17
Const $NDDE_INVALID_ITEM_LIST = 21
Const $NDDE_INVALID_ITEMNAME = 9
Const $NDDE_INVALID_LEVEL = 7
Const $NDDE_INVALID_PARAMETER = 6
Const $NDDE_INVALID_PASSWORD = 8
Const $NDDE_INVALID_SECURITY_DESC = 26
Const $NDDE_INVALID_SERVER = 4
Const $NDDE_INVALID_SESSION = 20
Const $NDDE_INVALID_SHARE = 5
Const $NDDE_INVALID_SPECIAL_COMMAND = 25
Const $NDDE_INVALID_TOPIC = 10
Const $NDDE_INVALID_WINDOW = 19
Const $NDDE_ITEM_ADVISE = 0x2
Const $NDDE_ITEM_GENERIC_ALL = BitOR($NDDE_ITEM_REQUEST, $NDDE_ITEM_ADVISE, $NDDE_ITEM_POKE, $Delete, $READ_CONTROL, $WRITE_DAC, $WRITE_OWNER)
Const $NDDE_ITEM_GENERIC_EXECUTE = 0
Const $NDDE_ITEM_GENERIC_READ = BitOR($NDDE_ITEM_REQUEST, $NDDE_ITEM_ADVISE)
Const $NDDE_ITEM_GENERIC_WRITE = $NDDE_ITEM_POKE
Const $NDDE_ITEM_POKE = 0x4
Const $NDDE_ITEM_REQUEST = 0x1
Const $NDDE_NO_ERROR = 0
Const $NDDE_NOT_IMPLEMENTED = 14
Const $NDDE_NOT_RUNNING = 18
Const $NDDE_OUT_OF_MEMORY = 12
Const $NDDE_REGISTRY_ERROR = 23
Const $NDDE_SHARE_ADD_ITEMS = 0x100
Const $NDDE_SHARE_ADVISE = 0x20
Const $NDDE_SHARE_ALREADY_EXIST = 15
Const $NDDE_SHARE_DATA_CORRUPTED = 22
Const $NDDE_SHARE_EXECUTE = 0x80
Const $NDDE_SHARE_GENERIC_ALL = BitOR($NDDE_SHARE_READ, $NDDE_SHARE_WRITE, $NDDE_SHARE_INITIATE_STATIC, $NDDE_SHARE_INITIATE_LINK, $NDDE_SHARE_REQUEST, $NDDE_SHARE_ADVISE, $NDDE_SHARE_POKE, $NDDE_SHARE_EXECUTE, $NDDE_SHARE_ADD_ITEMS, $NDDE_SHARE_LIST_ITEMS, $Delete, $READ_CONTROL, $WRITE_DAC, $WRITE_OWNER)
Const $NDDE_SHARE_GENERIC_EXECUTE = BitOR($NDDE_SHARE_INITIATE_STATIC, $NDDE_SHARE_INITIATE_LINK, $NDDE_SHARE_EXECUTE)
Const $NDDE_SHARE_GENERIC_READ = BitOR($NDDE_SHARE_READ, $NDDE_SHARE_INITIATE_STATIC, $NDDE_SHARE_REQUEST, $NDDE_SHARE_ADVISE, $NDDE_SHARE_LIST_ITEMS)
Const $NDDE_SHARE_GENERIC_WRITE = BitOR($NDDE_SHARE_INITIATE_STATIC, $NDDE_SHARE_INITIATE_LINK, $NDDE_SHARE_POKE, $Delete)
Const $NDDE_SHARE_INITIATE_LINK = 0x8
Const $NDDE_SHARE_INITIATE_STATIC = 0x4
Const $NDDE_SHARE_LIST_ITEMS = 0x200
Const $NDDE_SHARE_NOT_EXIST = 16
Const $NDDE_SHARE_POKE = 0x40
Const $NDDE_SHARE_READ = 0x1
Const $NDDE_SHARE_REQUEST = 0x10
Const $NDDE_SHARE_WRITE = 0x2
Const $NDDE_SHAREDB_ADD = 0x1
Const $NDDE_SHAREDB_ADMIN = BitOR($NDDE_SHAREDB_ADD, $NDDE_SHAREDB_DELETE, $NDDE_SHAREDB_LIST, $READ_CONTROL, $WRITE_DAC, $WRITE_OWNER)
Const $NDDE_SHAREDB_DELETE = 0x2
Const $NDDE_SHAREDB_EVERYONE = $NDDE_SHAREDB_LIST
Const $NDDE_SHAREDB_LIST = 0x4
Const $NDDE_SHAREDB_OPER = BitOR($NDDE_SHAREDB_ADD, $NDDE_SHAREDB_DELETE, $NDDE_SHAREDB_LIST)
Const $NDDE_SHAREDB_POWER = BitOR($NDDE_SHAREDB_ADD, $NDDE_SHAREDB_DELETE, $NDDE_SHAREDB_LIST)
Const $NDDE_SHAREDB_USER = BitOR($NDDE_SHAREDB_ADD, $NDDE_SHAREDB_DELETE, $NDDE_SHAREDB_LIST)
Const $NDDE_TRUST_CMD_SHOW = 0x10000000
Const $NDDE_TRUST_SHARE_DEL = 0x20000000
Const $NDDE_TRUST_SHARE_FAIL = 27
Const $NDDE_TRUST_SHARE_INIT = 0x40000000
Const $NDDE_TRUST_SHARE_START = 0x80000000
Const $NDDEF_NOCACHELOOKUP = 0x2
Const $NDDEF_NOPASSWORDPROMPT = 0x1
Const $NDDEF_STRIP_NDDE = 0x4
Const $nDesiredConvDllVersion = 1
Const $NDIS_802_3_MAC_OPTION_PRIORITY = 0x1
Const $NDIS_CO_MAC_OPTION_DYNAMIC_LINK_SPEED = 0x1
Const $NDIS_DEVICE_WAKE_UP_ENABLE = 0x1
Const $NDIS_MAC_OPTION_8021P_PRIORITY = 0x40
Const $NDIS_MAC_OPTION_COPY_LOOKAHEAD_DATA = 0x1
Const $NDIS_MAC_OPTION_EOTX_INDICATION = 0x20
Const $NDIS_MAC_OPTION_FULL_DUPLEX = 0x10
Const $NDIS_MAC_OPTION_NO_LOOPBACK = 0x8
Const $NDIS_MAC_OPTION_RECEIVE_SERIALIZED = 0x2
Const $NDIS_MAC_OPTION_RESERVED = 0x80000000
Const $NDIS_MAC_OPTION_TRANSFERS_NOT_PEND = 0x4
Const $NDIS_MEDIA_CAP_RECEIVE = 0x2
Const $NDIS_MEDIA_CAP_TRANSMIT = 0x1
Const $NDIS_PACKET_TYPE_ALL_FUNCTIONAL = 0x2000
Const $NDIS_PACKET_TYPE_ALL_LOCAL = 0x80
Const $NDIS_PACKET_TYPE_ALL_MULTICAST = 0x4
Const $NDIS_PACKET_TYPE_BROADCAST = 0x8
Const $NDIS_PACKET_TYPE_DIRECTED = 0x1
Const $NDIS_PACKET_TYPE_FUNCTIONAL = 0x4000
Const $NDIS_PACKET_TYPE_GROUP = 0x1000
Const $NDIS_PACKET_TYPE_MAC_FRAME = 0x8000
Const $NDIS_PACKET_TYPE_MULTICAST = 0x2
Const $NDIS_PACKET_TYPE_PROMISCUOUS = 0x20
Const $NDIS_PACKET_TYPE_SMT = 0x40
Const $NDIS_PACKET_TYPE_SOURCE_ROUTING = 0x10
Const $NDIS_PNP_WAKE_UP_LINK_CHANGE = 0x4
Const $NDIS_PNP_WAKE_UP_MAGIC_PACKET = 0x1
Const $NDIS_PNP_WAKE_UP_PATTERN_MATCH = 0x2
Const $NDIS_PROT_OPTION_ESTIMATED_LENGTH = 0x1
Const $NDIS_PROT_OPTION_NO_LOOPBACK = 0x2
Const $NDIS_PROT_OPTION_NO_RSVD_ON_RCVPKT = 0x4
Const $NDIS_PROTOCOL_ID_DEFAULT = 0x0
Const $NDIS_PROTOCOL_ID_IPX = 0x6
Const $NDIS_PROTOCOL_ID_MASK = 0xF
Const $NDIS_PROTOCOL_ID_MAX = 0xF
Const $NDIS_PROTOCOL_ID_NBF = 0x7
Const $NDIS_PROTOCOL_ID_TCP_IP = 0x2
Const $NDIS_RING_AUTO_REMOVAL_ERROR = 0x400
Const $NDIS_RING_COUNTER_OVERFLOW = 0x100
Const $NDIS_RING_HARD_ERROR = 0x4000
Const $NDIS_RING_LOBE_WIRE_FAULT = 0x800
Const $NDIS_RING_REMOVE_RECEIVED = 0x200
Const $NDIS_RING_RING_RECOVERY = 0x40
Const $NDIS_RING_SIGNAL_LOSS = 0x8000
Const $NDIS_RING_SINGLE_STATION = 0x80
Const $NDIS_RING_SOFT_ERROR = 0x2000
Const $NDIS_RING_TRANSMIT_BEACON = 0x1000
Const $NDR_ASCII_CHAR = 0x0
Const $NDR_BIG_ENDIAN = 0x0
Const $NDR_CHAR_REP_MASK = 0xF
Const $NDR_EBCDIC_CHAR = 0x1
Const $NDR_FLOAT_REP_MASK = 0xFF00
Const $NDR_IBM_FLOAT = 0x300
Const $NDR_IEEE_FLOAT = 0x0
Const $NDR_INT_REP_MASK = 0xF0
Const $NDR_LITTLE_ENDIAN = 0x10
Const $NDR_LOCAL_DATA_REPRESENTATION = 0x0
Const $NDR_LOCAL_ENDIAN = $NDR_BIG_ENDIAN
Const $NDR_VAX_FLOAT = 0x100
Const $NDW_INSTALLFLAG_CI_PICKED_OEM = 0x8000
Const $NDW_INSTALLFLAG_DIDFACTDEFS = 0x1
Const $NDW_INSTALLFLAG_EXPRESSINTRO = 0x400
Const $NDW_INSTALLFLAG_HARDWAREALLREADYIN = 0x2
Const $NDW_INSTALLFLAG_INSTALLSPECIFIC = 0x2000
Const $NDW_INSTALLFLAG_KNOWNCLASS = 0x80000
Const $NDW_INSTALLFLAG_NEEDSHUTDOWN = 0x200
Const $NDW_INSTALLFLAG_NODETECTEDDEVS = 0x1000
Const $NDW_INSTALLFLAG_PCMCIADEVICE = 0x20000
Const $NDW_INSTALLFLAG_PCMCIAMODE = 0x10000
Const $NDW_INSTALLFLAG_SKIPCLASSLIST = 0x4000
Const $NDW_INSTALLFLAG_SKIPISDEVINSTALLED = 0x800
Const $NDW_INSTALLFLAG_USERCANCEL = 0x40000
Const $NE_E_CANTCONNECT = 17
Const $NE_E_CONNBROKEN = 4
Const $NE_E_CONNBUSY = 3
Const $NE_E_CONNMODE = 12
Const $NE_E_GENERAL = 11
Const $NE_E_INVALIDCONN = 14
Const $NE_E_NAMENOTFOUND = 13
Const $NE_E_NETBUSY = 9
Const $NE_E_NETDATAERR = 15
Const $NE_E_NETNOTSTARTED = 7
Const $NE_E_NOACCESS = 2
Const $NE_E_NOMAP = 0
Const $NE_E_NOMEMORY = 1
Const $NE_E_NONETACCESS = 10
Const $NE_E_NORESOURCE = 8
Const $NE_E_SERVERNOTFOUND = 6
Const $NE_E_TOOMANYCONN = 5
Const $NE_E_TOOMANYFILES = 16
Const $NE_MAX_NETERROR = 17
Const $NEEDS_PREPROCESSING = 0x1
Const $NEEDS_SPOOLER = 0x2
Const $NEGOSSP_NAME = $NEGOSSP_NAME_A
Const $NEGOSSP_NAME_A = "Negotiate"
Const $NEGOSSP_NAME_W = "Negotiate"
Const $NEGOTIATE_ALLOW_NTLM = 0x10000000
Const $NEGOTIATE_MAX_PREFIX = 32
Const $NEGOTIATE_NEG_NTLM = 0x20000000
Const $NELOG_Access_File_Bad = $ERRLOG_BASE + 22
Const $NELOG_AT_cannot_read = $ERRLOG_BASE + 74
Const $NELOG_AT_cannot_write = $ERRLOG_BASE + 29
Const $NELOG_AT_Exec_Err = $ERRLOG_BASE + 78
Const $NELOG_AT_sched_err = $ERRLOG_BASE + 75
Const $NELOG_AT_schedule_file_created = $ERRLOG_BASE + 76
Const $NELOG_Build_Name = $ERRLOG_BASE + 70
Const $NELOG_Cant_Make_Msg_File = $ERRLOG_BASE + 30
Const $NELOG_DiskFT = $ERRLOG_BASE + 121
Const $NELOG_DriverNotLoaded = $ERRLOG2_BASE + 27
Const $NELOG_Entries_Lost = $ERRLOG_BASE + 14
Const $NELOG_Error_in_DLL = $ERRLOG_BASE + 156
Const $NELOG_Exec_Netservr_NoMem = $ERRLOG_BASE + 31
Const $NELOG_FailedToGetComputerName = $ERRLOG2_BASE + 26
Const $NELOG_FailedToRegisterSC = $ERRLOG2_BASE + 24
Const $NELOG_FailedToSetServiceStatus = $ERRLOG2_BASE + 25
Const $NELOG_File_Changed = $ERRLOG_BASE + 153
Const $NELOG_Files_Dont_Fit = $ERRLOG_BASE + 154
Const $NELOG_FT_ErrLog_Too_Large = $ERRLOG_BASE + 158
Const $NELOG_FT_Update_In_Progress = $ERRLOG_BASE + 159
Const $NELOG_HardErr_From_Server = $ERRLOG_BASE + 82
Const $NELOG_HotFix = $ERRLOG_BASE + 81
Const $NELOG_Init_Chardev_Err = $ERRLOG_BASE + 24
Const $NELOG_Init_Exec_Fail = $ERRLOG_BASE + 5
Const $NELOG_Init_OpenCreate_Err = $ERRLOG_BASE + 10
Const $NELOG_Init_Seg_Overflow = $ERRLOG_BASE + 20
Const $NELOG_Internal_Error = $ERRLOG_BASE + 0
Const $NELOG_Invalid_Config_File = $ERRLOG_BASE + 152
Const $NELOG_Invalid_Config_Line = $ERRLOG_BASE + 151
Const $NELOG_Ioctl_Error = $ERRLOG_BASE + 8
Const $NELOG_Lazy_Write_Err = $ERRLOG_BASE + 80
Const $NELOG_LocalSecFail1 = $ERRLOG_BASE + 83
Const $NELOG_LocalSecFail2 = $ERRLOG_BASE + 84
Const $NELOG_LocalSecFail3 = $ERRLOG_BASE + 85
Const $NELOG_LocalSecGeneralFail = $ERRLOG_BASE + 86
Const $NELOG_Mail_Slt_Err = $ERRLOG_BASE + 73
Const $NELOG_Mailslot_err = $ERRLOG_BASE + 27
Const $NELOG_Message_Send = $ERRLOG_BASE + 72
Const $NELOG_Missing_Parameter = $ERRLOG_BASE + 150
Const $NELOG_Msg_Log_Err = $ERRLOG_BASE + 50
Const $NELOG_Msg_Sem_Shutdown = $ERRLOG_BASE + 41
Const $NELOG_Msg_Shutdown = $ERRLOG_BASE + 40
Const $NELOG_Msg_Unexpected_SMB_Type = $ERRLOG_BASE + 52
Const $NELOG_Name_Expansion = $ERRLOG_BASE + 71
Const $NELOG_Ncb_Error = $ERRLOG_BASE + 6
Const $NELOG_Ncb_TooManyErr = $ERRLOG_BASE + 26
Const $NELOG_Net_Not_Started = $ERRLOG_BASE + 7
Const $NELOG_NetBios = $ERRLOG_BASE + 11
Const $NELOG_NetlogonAddNameFailure = $ERRLOG2_BASE + 41
Const $NELOG_NetlogonAuthDCFail = $ERRLOG_BASE + 110
Const $NELOG_NetlogonAuthNoDomainController = $ERRLOG2_BASE + 19
Const $NELOG_NetlogonAuthNoTrustLsaSecret = $ERRLOG2_BASE + 20
Const $NELOG_NetlogonAuthNoTrustSamAccount = $ERRLOG2_BASE + 21
Const $NELOG_NetlogonBadSiteName = $ERRLOG2_BASE + 79
Const $NELOG_NetlogonBadSubnetName = $ERRLOG2_BASE + 80
Const $NELOG_NetlogonBrowserDriver = $ERRLOG2_BASE + 40
Const $NELOG_NetlogonChangeLogCorrupt = $ERRLOG2_BASE + 5
Const $NELOG_NetlogonDcSiteCovered = $ERRLOG2_BASE + 84
Const $NELOG_NetlogonDcSiteNotCovered = $ERRLOG2_BASE + 85
Const $NELOG_NetlogonDownLevelLogoffFailed = $ERRLOG2_BASE + 8
Const $NELOG_NetlogonDownLevelLogonFailed = $ERRLOG2_BASE + 7
Const $NELOG_NetlogonDuplicateMachineAccounts = $ERRLOG2_BASE + 38
Const $NELOG_NetlogonDynamicDnsDeregisterFailure = $ERRLOG2_BASE + 75
Const $NELOG_NetlogonDynamicDnsFailure = $ERRLOG2_BASE + 82
Const $NELOG_NetlogonDynamicDnsRegisterFailure = $ERRLOG2_BASE + 74
Const $NELOG_NetlogonDynamicDnsServerFailure = $ERRLOG2_BASE + 81
Const $NELOG_NetlogonFailedAccountDelta = $ERRLOG2_BASE + 35
Const $NELOG_NetlogonFailedDnsHostNameUpdate = $ERRLOG2_BASE + 89
Const $NELOG_NetlogonFailedDomainDelta = $ERRLOG2_BASE + 29
Const $NELOG_NetlogonFailedFileCreate = $ERRLOG2_BASE + 76
Const $NELOG_NetlogonFailedGlobalGroupDelta = $ERRLOG2_BASE + 30
Const $NELOG_NetlogonFailedLocalGroupDelta = $ERRLOG2_BASE + 31
Const $NELOG_NetlogonFailedPolicyDelta = $ERRLOG2_BASE + 33
Const $NELOG_NetlogonFailedPrimary = $ERRLOG_BASE + 123
Const $NELOG_NetlogonFailedSecretDelta = $ERRLOG2_BASE + 36
Const $NELOG_NetlogonFailedSpnUpdate = $ERRLOG2_BASE + 88
Const $NELOG_NetlogonFailedToAddRpcInterface = $ERRLOG2_BASE + 2
Const $NELOG_NetlogonFailedToCreateShare = $ERRLOG2_BASE + 6
Const $NELOG_NetlogonFailedToReadMailslot = $ERRLOG2_BASE + 3
Const $NELOG_NetlogonFailedToRegisterSC = $ERRLOG2_BASE + 4
Const $NELOG_NetlogonFailedToUpdateTrustList = $ERRLOG2_BASE + 1
Const $NELOG_NetlogonFailedTrustedDomainDelta = $ERRLOG2_BASE + 34
Const $NELOG_NetlogonFailedUserDelta = $ERRLOG2_BASE + 32
Const $NELOG_NetlogonFullSyncCallFailed = $ERRLOG2_BASE + 14
Const $NELOG_NetlogonFullSyncCallSuccess = $ERRLOG2_BASE + 13
Const $NELOG_NetlogonFullSyncFailed = $ERRLOG2_BASE + 18
Const $NELOG_NetlogonFullSyncSuccess = $ERRLOG2_BASE + 17
Const $NELOG_NetlogonGcSiteCovered = $ERRLOG2_BASE + 86
Const $NELOG_NetlogonGcSiteNotCovered = $ERRLOG2_BASE + 87
Const $NELOG_NetlogonGetSubnetToSite = $ERRLOG2_BASE + 77
Const $NELOG_NetlogonLanmanBdcsNotAllowed = $ERRLOG2_BASE + 72
Const $NELOG_NetlogonNoDynamicDns = $ERRLOG2_BASE + 73
Const $NELOG_NetlogonNoSiteForClient = $ERRLOG2_BASE + 78
Const $NELOG_NetlogonNTLogoffFailed = $ERRLOG2_BASE + 10
Const $NELOG_NetlogonNTLogonFailed = $ERRLOG2_BASE + 9
Const $NELOG_NetlogonPartialSyncCallFailed = $ERRLOG2_BASE + 12
Const $NELOG_NetlogonPartialSyncCallSuccess = $ERRLOG2_BASE + 11
Const $NELOG_NetlogonPartialSyncFailed = $ERRLOG2_BASE + 16
Const $NELOG_NetlogonPartialSyncSuccess = $ERRLOG2_BASE + 15
Const $NELOG_NetlogonPasswdSetFailed = $ERRLOG_BASE + 124
Const $NELOG_NetlogonRequireSignOrSealError = $ERRLOG_BASE + 127
Const $NELOG_NetlogonRpcCallCancelled = $ERRLOG2_BASE + 83
Const $NELOG_NetlogonServerAuthFailed = $ERRLOG2_BASE + 22
Const $NELOG_NetlogonServerAuthNoTrustSamAccount = $ERRLOG2_BASE + 23
Const $NELOG_NetlogonSessionTypeWrong = $ERRLOG2_BASE + 70
Const $NELOG_NetlogonSSIInitError = $ERRLOG2_BASE + 0
Const $NELOG_NetlogonSyncError = $ERRLOG_BASE + 126
Const $NELOG_NetlogonSystemError = $ERRLOG2_BASE + 37
Const $NELOG_NetlogonTooManyGlobalGroups = $ERRLOG2_BASE + 39
Const $NELOG_NetlogonTrackingError = $ERRLOG_BASE + 125
Const $NELOG_NetWkSta_Internal_Error = $ERRLOG_BASE + 90
Const $NELOG_NetWkSta_NCB_Err = $ERRLOG_BASE + 95
Const $NELOG_NetWkSta_No_Resource = $ERRLOG_BASE + 91
Const $NELOG_NetWkSta_Reset_Err = $ERRLOG_BASE + 97
Const $NELOG_NetWkSta_SMB_Err = $ERRLOG_BASE + 92
Const $NELOG_NetWkSta_Stuck_VC_Err = $ERRLOG_BASE + 94
Const $NELOG_NetWkSta_Too_Many = $ERRLOG_BASE + 98
Const $NELOG_NetWkSta_VC_Err = $ERRLOG_BASE + 93
Const $NELOG_NetWkSta_Write_Behind_Err = $ERRLOG_BASE + 96
Const $NELOG_NoTranportLoaded = $ERRLOG2_BASE + 28
Const $NELOG_OEM_Code = $ERRLOG_BASE + 199
Const $NELOG_ReleaseMem_Alert = $ERRLOG_BASE + 28
Const $NELOG_Remote_API = $ERRLOG_BASE + 25
Const $NELOG_ReplAccessDenied = $ERRLOG_BASE + 122
Const $NELOG_ReplBadExport = $ERRLOG_BASE + 119
Const $NELOG_ReplBadImport = $ERRLOG_BASE + 118
Const $NELOG_ReplBadMsg = $ERRLOG_BASE + 115
Const $NELOG_ReplCannotMasterDir = $ERRLOG_BASE + 107
Const $NELOG_ReplLogonFailed = $ERRLOG_BASE + 111
Const $NELOG_ReplLostMaster = $ERRLOG_BASE + 109
Const $NELOG_ReplMaxFiles = $ERRLOG_BASE + 113
Const $NELOG_ReplMaxTreeDepth = $ERRLOG_BASE + 114
Const $NELOG_ReplNetErr = $ERRLOG_BASE + 112
Const $NELOG_ReplSignalFileErr = $ERRLOG_BASE + 120
Const $NELOG_ReplSysErr = $ERRLOG_BASE + 116
Const $NELOG_ReplUpdateError = $ERRLOG_BASE + 108
Const $NELOG_ReplUserCurDir = $ERRLOG_BASE + 106
Const $NELOG_ReplUserLoged = $ERRLOG_BASE + 117
Const $NELOG_Resource_Shortage = $ERRLOG_BASE + 1
Const $NELOG_RplAdapterResource = $ERRLOG2_BASE + 56
Const $NELOG_RplBackupDatabase = $ERRLOG2_BASE + 65
Const $NELOG_RplCheckConfigs = $ERRLOG2_BASE + 60
Const $NELOG_RplCheckSecurity = $ERRLOG2_BASE + 64
Const $NELOG_RplCreateProfiles = $ERRLOG2_BASE + 61
Const $NELOG_RplFileCopy = $ERRLOG2_BASE + 57
Const $NELOG_RplFileDelete = $ERRLOG2_BASE + 58
Const $NELOG_RplFilePerms = $ERRLOG2_BASE + 59
Const $NELOG_RplInitDatabase = $ERRLOG2_BASE + 66
Const $NELOG_RplInitRestoredDatabase = $ERRLOG2_BASE + 69
Const $NELOG_RplMessages = $ERRLOG2_BASE + 42
Const $NELOG_RplRegistry = $ERRLOG2_BASE + 62
Const $NELOG_RplReplaceRPLDISK = $ERRLOG2_BASE + 63
Const $NELOG_RplRestoreDatabaseFailure = $ERRLOG2_BASE + 67
Const $NELOG_RplRestoreDatabaseSuccess = $ERRLOG2_BASE + 68
Const $NELOG_RplSystem = $ERRLOG2_BASE + 44
Const $NELOG_RplUpgradeDBTo40 = $ERRLOG2_BASE + 71
Const $NELOG_RplWkstaBbcFile = $ERRLOG2_BASE + 51
Const $NELOG_RplWkstaFileChecksum = $ERRLOG2_BASE + 49
Const $NELOG_RplWkstaFileLineCount = $ERRLOG2_BASE + 50
Const $NELOG_RplWkstaFileOpen = $ERRLOG2_BASE + 46
Const $NELOG_RplWkstaFileRead = $ERRLOG2_BASE + 47
Const $NELOG_RplWkstaFileSize = $ERRLOG2_BASE + 52
Const $NELOG_RplWkstaInternal = $ERRLOG2_BASE + 53
Const $NELOG_RplWkstaMemory = $ERRLOG2_BASE + 48
Const $NELOG_RplWkstaNetwork = $ERRLOG2_BASE + 55
Const $NELOG_RplWkstaTimeout = $ERRLOG2_BASE + 45
Const $NELOG_RplWkstaWrongVersion = $ERRLOG2_BASE + 54
Const $NELOG_RplXnsBoot = $ERRLOG2_BASE + 43
Const $NELOG_Server_Lock_Failure = $ERRLOG_BASE + 32
Const $NELOG_Service_Fail = $ERRLOG_BASE + 13
Const $NELOG_SMB_Illegal = $ERRLOG_BASE + 12
Const $NELOG_Srv_Close_Failure = $ERRLOG_BASE + 105
Const $NELOG_Srv_No_Mem_Grow = $ERRLOG_BASE + 21
Const $NELOG_Srv_Thread_Failure = $ERRLOG_BASE + 104
Const $NELOG_Srvnet_NB_Open = $ERRLOG_BASE + 77
Const $NELOG_Srvnet_Not_Started = $ERRLOG_BASE + 23
Const $NELOG_System_Error = $ERRLOG_BASE + 157
Const $NELOG_System_Semaphore = $ERRLOG_BASE + 9
Const $NELOG_Unable_To_Lock_Segment = $ERRLOG_BASE + 2
Const $NELOG_Unable_To_Unlock_Segment = $ERRLOG_BASE + 3
Const $NELOG_Uninstall_Service = $ERRLOG_BASE + 4
Const $NELOG_UPS_CannotOpenDriver = $ERRLOG_BASE + 133
Const $NELOG_UPS_CmdFileConfig = $ERRLOG_BASE + 135
Const $NELOG_UPS_CmdFileError = $ERRLOG_BASE + 132
Const $NELOG_UPS_CmdFileExec = $ERRLOG_BASE + 136
Const $NELOG_UPS_PowerBack = $ERRLOG_BASE + 134
Const $NELOG_UPS_PowerOut = $ERRLOG_BASE + 130
Const $NELOG_UPS_Shutdown = $ERRLOG_BASE + 131
Const $NELOG_VIO_POPUP_ERR = $ERRLOG_BASE + 51
Const $NELOG_Wksta_Bad_Mailslot_SMB = $ERRLOG_BASE + 65
Const $NELOG_Wksta_BiosThreadFailure = $ERRLOG_BASE + 62
Const $NELOG_Wksta_Compname = $ERRLOG_BASE + 61
Const $NELOG_Wksta_HostTab_Full = $ERRLOG_BASE + 64
Const $NELOG_Wksta_Infoseg = $ERRLOG_BASE + 60
Const $NELOG_Wksta_IniSeg = $ERRLOG_BASE + 63
Const $NELOG_Wksta_SSIRelogon = $ERRLOG_BASE + 67
Const $NELOG_Wksta_UASInit = $ERRLOG_BASE + 66
Const $NELOG_Wrong_DLL_Version = $ERRLOG_BASE + 155
Const $NERR_AccountExpired = $NERR_BASE + 139
Const $NERR_AccountUndefined = $NERR_BASE + 138
Const $NERR_AcctLimitExceeded = $NERR_BASE + 334
Const $NERR_ACFFileIOFail = $NERR_BASE + 129
Const $NERR_ACFNoParent = $NERR_BASE + 132
Const $NERR_ACFNoRoom = $NERR_BASE + 128
Const $NERR_ACFNotFound = $NERR_BASE + 119
Const $NERR_ACFNotLoaded = $NERR_BASE + 127
Const $NERR_ACFTooManyLists = $NERR_BASE + 130
Const $NERR_ActiveConns = $NERR_BASE + 302
Const $NERR_AddForwarded = $NERR_BASE + 175
Const $NERR_AlertExists = $NERR_BASE + 330
Const $NERR_AlreadyExists = $NERR_BASE + 176
Const $NERR_AlreadyForwarded = $NERR_BASE + 174
Const $NERR_AlreadyLoggedOn = $NERR_BASE + 100
Const $NERR_BadAsgType = $NERR_BASE + 151
Const $NERR_BadComponent = $NERR_BASE + 256
Const $NERR_BadControlRecv = $NERR_BASE + 93
Const $NERR_BadDest = $NERR_BASE + 282
Const $NERR_BadDev = $NERR_BASE + 241
Const $NERR_BadDevString = $NERR_BASE + 240
Const $NERR_BadDosFunction = $NERR_BASE + 402
Const $NERR_BadDosRetCode = $NERR_BASE + 400
Const $NERR_BadEventName = $NERR_BASE + 43
Const $NERR_BadFileCheckSum = $NERR_BASE + 404
Const $NERR_BadPassword = $NERR_BASE + 103
Const $NERR_BadPasswordCore = $NERR_BASE + 303
Const $NERR_BadQueueDevString = $NERR_BASE + 234
Const $NERR_BadQueuePriority = $NERR_BASE + 235
Const $NERR_BadReceive = $NERR_BASE + 182
Const $NERR_BadRecipient = $NERR_BASE + 333
Const $NERR_BadServiceName = $NERR_BASE + 85
Const $NERR_BadServiceProgName = $NERR_BASE + 88
Const $NERR_BadSource = $NERR_BASE + 281
Const $NERR_BadTransactConfig = $NERR_BASE + 41
Const $NERR_BadUasConfig = $NERR_BASE + 350
Const $NERR_BadUsername = $NERR_BASE + 102
Const $NERR_BASE = 2100
Const $NERR_BrowserConfiguredToNotRun = $NERR_BASE + 450
Const $NERR_BrowserNotStarted = $NERR_BASE + 39
Const $NERR_BrowserTableIncomplete = $NERR_BASE + 219
Const $NERR_BufTooSmall = $NERR_BASE + 23
Const $NERR_CallingRplSrvr = $NERR_BASE + 415
Const $NERR_CanNotGrowSegment = $NERR_BASE + 133
Const $NERR_CanNotGrowUASFile = $NERR_BASE + 356
Const $NERR_CantConnectRplSrvr = $NERR_BASE + 413
Const $NERR_CantOpenImageFile = $NERR_BASE + 414
Const $NERR_CantType = $NERR_BASE + 257
Const $NERR_CfgCompNotFound = $NERR_BASE + 46
Const $NERR_CfgParamNotFound = $NERR_BASE + 47
Const $NERR_ClientNameNotFound = $NERR_BASE + 212
Const $NERR_CommDevInUse = $NERR_BASE + 243
Const $NERR_ComputerAccountNotFound = $NERR_BASE + 597
Const $NERR_DatabaseUpToDate = $NERR_BASE + 148
Const $NERR_DataTypeInvalid = $NERR_BASE + 67
Const $NERR_DCNotFound = $NERR_BASE + 353
Const $NERR_DefaultJoinRequired = $NERR_BASE + 594
Const $NERR_DelComputerName = $NERR_BASE + 178
Const $NERR_DeleteLater = $NERR_BASE + 198
Const $NERR_DestExists = $NERR_BASE + 53
Const $NERR_DestIdle = $NERR_BASE + 58
Const $NERR_DestInvalidOp = $NERR_BASE + 59
Const $NERR_DestInvalidState = $NERR_BASE + 62
Const $NERR_DestNoRoom = $NERR_BASE + 57
Const $NERR_DestNotFound = $NERR_BASE + 52
Const $NERR_DeviceIsShared = $NERR_BASE + 152
Const $NERR_DeviceNotShared = $NERR_BASE + 211
Const $NERR_DeviceShareConflict = $NERR_BASE + 218
Const $NERR_DevInUse = $NERR_BASE + 304
Const $NERR_DevInvalidOpCode = $NERR_BASE + 231
Const $NERR_DevNotFound = $NERR_BASE + 232
Const $NERR_DevNotOpen = $NERR_BASE + 233
Const $NERR_DevNotRedirected = $NERR_BASE + 7
Const $NERR_DfsAlreadyShared = $NERR_BASE + 564
Const $NERR_DfsBadRenamePath = $NERR_BASE + 571
Const $NERR_DfsCantCreateJunctionPoint = $NERR_BASE + 569
Const $NERR_DfsCantRemoveDfsRoot = $NERR_BASE + 582
Const $NERR_DfsCantRemoveLastServerShare = $NERR_BASE + 577
Const $NERR_DfsChildOrParentInDfs = $NERR_BASE + 583
Const $NERR_DfsCyclicalName = $NERR_BASE + 574
Const $NERR_DfsDataIsIdentical = $NERR_BASE + 581
Const $NERR_DfsDuplicateService = $NERR_BASE + 576
Const $NERR_DfsInconsistent = $NERR_BASE + 579
Const $NERR_DfsInternalCorruption = $NERR_BASE + 560
Const $NERR_DfsInternalError = $NERR_BASE + 590
Const $NERR_DfsLeafVolume = $NERR_BASE + 567
Const $NERR_DfsNoSuchServer = $NERR_BASE + 573
Const $NERR_DfsNoSuchShare = $NERR_BASE + 565
Const $NERR_DfsNoSuchVolume = $NERR_BASE + 562
Const $NERR_DfsNotALeafVolume = $NERR_BASE + 566
Const $NERR_DfsNotSupportedInServerDfs = $NERR_BASE + 575
Const $NERR_DfsServerNotDfsAware = $NERR_BASE + 570
Const $NERR_DfsServerUpgraded = $NERR_BASE + 580
Const $NERR_DfsVolumeAlreadyExists = $NERR_BASE + 563
Const $NERR_DfsVolumeDataCorrupt = $NERR_BASE + 561
Const $NERR_DfsVolumeHasMultipleServers = $NERR_BASE + 568
Const $NERR_DfsVolumeIsInterDfs = $NERR_BASE + 578
Const $NERR_DfsVolumeIsOffline = $NERR_BASE + 572
Const $NERR_DifferentServers = $NERR_BASE + 283
Const $NERR_DriverNotFound = $NERR_BASE + 66
Const $NERR_DuplicateName = $NERR_BASE + 197
Const $NERR_DuplicateShare = $NERR_BASE + 18
Const $NERR_DupNameReboot = $NERR_BASE + 44
Const $NERR_ErrCommRunSrv = $NERR_BASE + 289
Const $NERR_ErrorExecingGhost = $NERR_BASE + 291
Const $NERR_ExecFailure = $NERR_BASE + 215
Const $NERR_FileIdNotFound = $NERR_BASE + 214
Const $NERR_GroupExists = $NERR_BASE + 123
Const $NERR_GroupNotFound = $NERR_BASE + 120
Const $NERR_GrpMsgProcessor = $NERR_BASE + 180
Const $NERR_ImageParamErr = $NERR_BASE + 408
Const $NERR_IncompleteDel = $NERR_BASE + 199
Const $NERR_InternalError = $NERR_BASE + 40
Const $NERR_InUseBySpooler = $NERR_BASE + 242
Const $NERR_InvalidAPI = $NERR_BASE + 42
Const $NERR_InvalidComputer = $NERR_BASE + 251
Const $NERR_InvalidDatabase = $NERR_BASE + 147
Const $NERR_InvalidDevice = $NERR_BASE + 194
Const $NERR_InvalidLana = $NERR_BASE + 300
Const $NERR_InvalidLogonHours = $NERR_BASE + 141
Const $NERR_InvalidLogSeek = $NERR_BASE + 340
Const $NERR_InvalidMaxUsers = $NERR_BASE + 22
Const $NERR_InvalidUASOp = $NERR_BASE + 351
Const $NERR_InvalidWorkgroupName = $NERR_BASE + 595
Const $NERR_InvalidWorkstation = $NERR_BASE + 140
Const $NERR_IsDfsShare = $NERR_BASE + 221
Const $NERR_ItemNotFound = $NERR_BASE + 15
Const $NERR_JobInvalidState = $NERR_BASE + 64
Const $NERR_JobNoRoom = $NERR_BASE + 56
Const $NERR_JobNotFound = $NERR_BASE + 51
Const $NERR_LanmanIniError = $NERR_BASE + 31
Const $NERR_LastAdmin = $NERR_BASE + 352
Const $NERR_LineTooLong = $NERR_BASE + 49
Const $NERR_LocalDrive = $NERR_BASE + 305
Const $NERR_LocalForward = $NERR_BASE + 179
Const $NERR_LogFileChanged = $NERR_BASE + 278
Const $NERR_LogFileCorrupt = $NERR_BASE + 279
Const $NERR_LogonDomainExists = $NERR_BASE + 116
Const $NERR_LogonNoUserPath = $NERR_BASE + 111
Const $NERR_LogonScriptError = $NERR_BASE + 112
Const $NERR_LogonServerConflict = $NERR_BASE + 110
Const $NERR_LogonServerNotFound = $NERR_BASE + 115
Const $NERR_LogonsPaused = $NERR_BASE + 109
Const $NERR_LogonTrackingError = $NERR_BASE + 354
Const $NERR_LogOverflow = $NERR_BASE + 277
Const $NERR_MaxLenExceeded = $NERR_BASE + 254
Const $NERR_MsgAlreadyStarted = $NERR_BASE + 171
Const $NERR_MsgInitFailed = $NERR_BASE + 172
Const $NERR_MsgNotStarted = $NERR_BASE + 184
Const $NERR_MultipleNets = $NERR_BASE + 200
Const $NERR_NameInUse = $NERR_BASE + 183
Const $NERR_NameNotForwarded = $NERR_BASE + 188
Const $NERR_NameNotFound = $NERR_BASE + 173
Const $NERR_NameUsesIncompatibleCodePage = $NERR_BASE + 596
Const $NERR_NetlogonNotStarted = $NERR_BASE + 355
Const $NERR_NetNameNotFound = $NERR_BASE + 210
Const $NERR_NetNotStarted = $NERR_BASE + 2
Const $NERR_NetworkError = $NERR_BASE + 36
Const $NERR_NoAlternateServers = $NERR_BASE + 367
Const $NERR_NoCommDevs = $NERR_BASE + 237
Const $NERR_NoComputerName = $NERR_BASE + 170
Const $NERR_NoForwardName = $NERR_BASE + 186
Const $NERR_NonDosFloppyUsed = $NERR_BASE + 410
Const $NERR_NoNetworkResource = $NERR_BASE + 5
Const $NERR_NonValidatedLogon = $NERR_BASE + 117
Const $NERR_NoRoom = $NERR_BASE + 19
Const $NERR_NoRplBootSystem = $NERR_BASE + 405
Const $NERR_NoSuchAlert = $NERR_BASE + 332
Const $NERR_NoSuchConnection = $NERR_BASE + 362
Const $NERR_NoSuchServer = $NERR_BASE + 360
Const $NERR_NoSuchSession = $NERR_BASE + 361
Const $NERR_NotInCache = $NERR_BASE + 135
Const $NERR_NotInDispatchTbl = $NERR_BASE + 92
Const $NERR_NotLocalDomain = $NERR_BASE + 220
Const $NERR_NotLocalName = $NERR_BASE + 185
Const $NERR_NotLoggedOn = $NERR_BASE + 101
Const $NERR_NotPrimary = $NERR_BASE + 126
Const $NERR_OpenFiles = $NERR_BASE + 301
Const $NERR_PasswordCantChange = $NERR_BASE + 143
Const $NERR_PasswordExpired = $NERR_BASE + 142
Const $NERR_PasswordHistConflict = $NERR_BASE + 144
Const $NERR_PasswordMismatch = $NERR_BASE + 358
Const $NERR_PasswordTooRecent = $NERR_BASE + 146
Const $NERR_PasswordTooShort = $NERR_BASE + 145
Const $NERR_PausedRemote = $NERR_BASE + 181
Const $NERR_ProcNoRespond = $NERR_BASE + 60
Const $NERR_ProcNotFound = $NERR_BASE + 68
Const $NERR_ProfileCleanup = $NERR_BASE + 272
Const $NERR_ProfileFileTooBig = $NERR_BASE + 270
Const $NERR_ProfileLoadErr = $NERR_BASE + 274
Const $NERR_ProfileOffset = $NERR_BASE + 271
Const $NERR_ProfileSaveErr = $NERR_BASE + 275
Const $NERR_ProfileUnknownCmd = $NERR_BASE + 273
Const $NERR_ProgNeedsExtraMem = $NERR_BASE + 401
Const $NERR_QExists = $NERR_BASE + 54
Const $NERR_QInvalidState = $NERR_BASE + 63
Const $NERR_QNoRoom = $NERR_BASE + 55
Const $NERR_QNotFound = $NERR_BASE + 50
Const $NERR_QueueNotFound = $NERR_BASE + 238
Const $NERR_RedirectedPath = $NERR_BASE + 17
Const $NERR_RemoteBootFailed = $NERR_BASE + 403
Const $NERR_RemoteErr = $NERR_BASE + 27
Const $NERR_RemoteFull = $NERR_BASE + 187
Const $NERR_RemoteOnly = $NERR_BASE + 6
Const $NERR_ResourceExists = $NERR_BASE + 125
Const $NERR_ResourceNotFound = $NERR_BASE + 122
Const $NERR_RPL_CONNECTED = $NERR_BASE + 419
Const $NERR_RplAdapterInfoCorrupted = $NERR_BASE + 525
Const $NERR_RplAdapterNameUnavailable = $NERR_BASE + 533
Const $NERR_RplAdapterNotFound = $NERR_BASE + 537
Const $NERR_RplBackupDatabase = $NERR_BASE + 536
Const $NERR_RplBadDatabase = $NERR_BASE + 512
Const $NERR_RplBadRegistry = $NERR_BASE + 511
Const $NERR_RplBootInfoCorrupted = $NERR_BASE + 528
Const $NERR_RplBootInUse = $NERR_BASE + 535
Const $NERR_RplBootNameUnavailable = $NERR_BASE + 540
Const $NERR_RplBootNotFound = $NERR_BASE + 531
Const $NERR_RplBootRestart = $NERR_BASE + 411
Const $NERR_RplBootServiceTerm = $NERR_BASE + 417
Const $NERR_RplBootStartFailed = $NERR_BASE + 418
Const $NERR_RplCannotEnum = $NERR_BASE + 515
Const $NERR_RplConfigInfoCorrupted = $NERR_BASE + 523
Const $NERR_RplConfigNameUnavailable = $NERR_BASE + 541
Const $NERR_RplConfigNotEmpty = $NERR_BASE + 534
Const $NERR_RplConfigNotFound = $NERR_BASE + 524
Const $NERR_RplIncompatibleProfile = $NERR_BASE + 532
Const $NERR_RplInternal = $NERR_BASE + 526
Const $NERR_RplLoadrDiskErr = $NERR_BASE + 407
Const $NERR_RplLoadrNetBiosErr = $NERR_BASE + 406
Const $NERR_RplNeedsRPLUSERAcct = $NERR_BASE + 530
Const $NERR_RplNoAdaptersStarted = $NERR_BASE + 510
Const $NERR_RplNotRplServer = $NERR_BASE + 514
Const $NERR_RplProfileInfoCorrupted = $NERR_BASE + 519
Const $NERR_RplProfileNameUnavailable = $NERR_BASE + 521
Const $NERR_RplProfileNotEmpty = $NERR_BASE + 522
Const $NERR_RplProfileNotFound = $NERR_BASE + 520
Const $NERR_RplRplfilesShare = $NERR_BASE + 513
Const $NERR_RplSrvrCallFailed = $NERR_BASE + 412
Const $NERR_RplVendorInfoCorrupted = $NERR_BASE + 527
Const $NERR_RplVendorNameUnavailable = $NERR_BASE + 539
Const $NERR_RplVendorNotFound = $NERR_BASE + 538
Const $NERR_RplWkstaInfoCorrupted = $NERR_BASE + 516
Const $NERR_RplWkstaNameUnavailable = $NERR_BASE + 518
Const $NERR_RplWkstaNeedsUserAcct = $NERR_BASE + 529
Const $NERR_RplWkstaNotFound = $NERR_BASE + 517
Const $NERR_RunSrvPaused = $NERR_BASE + 285
Const $NERR_ServerNotStarted = $NERR_BASE + 14
Const $NERR_ServiceCtlBusy = $NERR_BASE + 87
Const $NERR_ServiceCtlNotValid = $NERR_BASE + 91
Const $NERR_ServiceCtlTimeout = $NERR_BASE + 86
Const $NERR_ServiceEntryLocked = $NERR_BASE + 83
Const $NERR_ServiceInstalled = $NERR_BASE + 82
Const $NERR_ServiceKillProc = $NERR_BASE + 90
Const $NERR_ServiceNotCtrl = $NERR_BASE + 89
Const $NERR_ServiceNotInstalled = $NERR_BASE + 84
Const $NERR_ServiceNotStarting = $NERR_BASE + 94
Const $NERR_ServiceTableFull = $NERR_BASE + 81
Const $NERR_ServiceTableLocked = $NERR_BASE + 80
Const $NERR_SetupAlreadyJoined = $NERR_BASE + 591
Const $NERR_SetupDomainController = $NERR_BASE + 593
Const $NERR_SetupNotJoined = $NERR_BASE + 592
Const $NERR_ShareMem = $NERR_BASE + 4
Const $NERR_ShareNotFound = $NERR_BASE + 292
Const $NERR_SourceIsDir = $NERR_BASE + 280
Const $NERR_SpeGroupOp = $NERR_BASE + 134
Const $NERR_SpoolerNotLoaded = $NERR_BASE + 61
Const $NERR_SpoolNoMemory = $NERR_BASE + 65
Const $NERR_StandaloneLogon = $NERR_BASE + 114
Const $NERR_StartingRplBoot = $NERR_BASE + 416
Const $NERR_Success = 0
Const $NERR_SyncRequired = $NERR_BASE + 149
Const $NERR_TimeDiffAtDC = $NERR_BASE + 357
Const $NERR_TmpFile = $NERR_BASE + 216
Const $NERR_TooManyAlerts = $NERR_BASE + 331
Const $NERR_TooManyConnections = $NERR_BASE + 365
Const $NERR_TooManyEntries = $NERR_BASE + 262
Const $NERR_TooManyFiles = $NERR_BASE + 366
Const $NERR_TooManyImageParams = $NERR_BASE + 409
Const $NERR_TooManyItems = $NERR_BASE + 21
Const $NERR_TooManyNames = $NERR_BASE + 177
Const $NERR_TooManyServers = $NERR_BASE + 363
Const $NERR_TooManySessions = $NERR_BASE + 364
Const $NERR_TooMuchData = $NERR_BASE + 217
Const $NERR_TruncatedBroadcast = $NERR_BASE + 189
Const $NERR_TryDownLevel = $NERR_BASE + 370
Const $NERR_UnableToAddName_F = $NERR_BASE + 105
Const $NERR_UnableToAddName_W = $NERR_BASE + 104
Const $NERR_UnableToDelName_F = $NERR_BASE + 107
Const $NERR_UnableToDelName_W = $NERR_BASE + 106
Const $NERR_UnknownDevDir = $NERR_BASE + 16
Const $NERR_UnknownServer = $NERR_BASE + 3
Const $NERR_UPSDriverNotStarted = $NERR_BASE + 380
Const $NERR_UPSInvalidCommPort = $NERR_BASE + 382
Const $NERR_UPSInvalidConfig = $NERR_BASE + 381
Const $NERR_UPSShutdownFailed = $NERR_BASE + 384
Const $NERR_UPSSignalAsserted = $NERR_BASE + 383
Const $NERR_UseNotFound = $NERR_BASE + 150
Const $NERR_UserExists = $NERR_BASE + 124
Const $NERR_UserInGroup = $NERR_BASE + 136
Const $NERR_UserLogon = $NERR_BASE + 131
Const $NERR_UserNotFound = $NERR_BASE + 121
Const $NERR_UserNotInGroup = $NERR_BASE + 137
Const $NERR_WkstaInconsistentState = $NERR_BASE + 37
Const $NERR_WkstaNotStarted = $NERR_BASE + 38
Const $NERR_WriteFault = $NERR_BASE + 195
Const $NET_CLASS = 0
Const $NET_COMMENT = 4
Const $NET_COMMON_NAME = 1
Const $NET_DFS_SETDC_FLAGS = 0x0
Const $NET_DFS_SETDC_INITPKT = 0x2
Const $NET_DFS_SETDC_TIMEOUT = 0x1
Const $NET_DISPLAY_NAME = 2
Const $NET_E_ADDRINUSE = 0x80040307
Const $NET_E_BADSEQUENCE = 0x80040304
Const $NET_E_CONNABORTED = 0x8004030C
Const $NET_E_CONNREFUSED = 0x8004030E
Const $NET_E_DISCONNECTED = 0x80040303
Const $NET_E_GENERAL = 0x80040300
Const $NET_E_HOSTLOOKUPFAILED = 0x8004030B
Const $NET_E_HOSTNOTFOUND = 0x8004030A
Const $NET_E_INVALIDPARAMS = 0x80040308
Const $NET_E_NETDOWN = 0x80040305
Const $NET_E_OPERATIONINPROGRESS = 0x80040309
Const $NET_E_RESOURCES = 0x80040302
Const $NET_E_TIMEOUT = 0x8004030F
Const $NET_E_UNEXPECTED = 0x80040301
Const $NET_E_WINSOCKNOTINITIALIZED = 0x80040306
Const $NET_HOME_SERVER = 3
Const $NET_NOT_AVAIL = 0x2
Const $NET_S_MOREDATA = 0x4030D
Const $NET_SEARCH = 0x1
Const $NETBIOS_GROUP_NAME = 0x1
Const $NETBIOS_NAME_LEN = 16
Const $NETBIOS_NAME_LENGTH = 16
Const $NETBIOS_TYPE_QUICK_GROUP = 0x3
Const $NETBIOS_TYPE_QUICK_UNIQUE = 0x2
Const $NETBIOS_UNIQUE_NAME = 0x0
Const $NETERR_RING_STATUS_AUTO_REMOVAL_ERROR = 0x400
Const $NETERR_RING_STATUS_COUNTER_OVERFLOW = 0x100
Const $NETERR_RING_STATUS_HARD_ERROR = 0x4000
Const $NETERR_RING_STATUS_LOBE_WIRE_FAULT = 0x800
Const $NETERR_RING_STATUS_RECOVERY = 0x40
Const $NETERR_RING_STATUS_REMOTE_RECEIVED = 0x200
Const $NETERR_RING_STATUS_SIGNAL_LOST = 0x8000
Const $NETERR_RING_STATUS_SIGNAL_STATION = 0x80
Const $NETERR_RING_STATUS_SOFT_ERROR = 0x2000
Const $NETERR_RING_STATUS_TRANSMIT_BEACON = 0x1000
Const $NETERR_RING_STOP_CAPTURE = 0x8E00
Const $NETEXPORT_WRITE_ERROR = 0xC0000132
Const $NETINFO_DISKRED = 0x4
Const $NETINFO_DLL16 = 0x1
Const $NETINFO_PRINTERRED = 0x8
Const $NETLOGON_CONTROL_BACKUP_CHANGE_LOG = 0xFFFC
Const $NETLOGON_CONTROL_BREAKPOINT = 0xFFFF
Const $NETLOGON_CONTROL_CHANGE_PASSWORD = 9
Const $NETLOGON_CONTROL_FIND_USER = 8
Const $NETLOGON_CONTROL_PDC_REPLICATE = 4
Const $NETLOGON_CONTROL_QUERY = 1
Const $NETLOGON_CONTROL_REDISCOVER = 5
Const $NETLOGON_CONTROL_REPLICATE = 2
Const $NETLOGON_CONTROL_SET_DBFLAG = 0xFFFE
Const $NETLOGON_CONTROL_SYNCHRONIZE = 3
Const $NETLOGON_CONTROL_TC_QUERY = 6
Const $NETLOGON_CONTROL_TRANSPORT_NOTIFY = 7
Const $NETLOGON_CONTROL_TRUNCATE_LOG = 0xFFFD
Const $NETLOGON_CONTROL_UNLOAD_NETLOGON_DLL = 0xFFFB
Const $NETLOGON_FULL_SYNC_REPLICATION = 0x4
Const $NETLOGON_HAS_IP = 0x10
Const $NETLOGON_HAS_TIMESERV = 0x20
Const $NETLOGON_REDO_NEEDED = 0x8
Const $NETLOGON_REPLICATION_IN_PROGRESS = 0x2
Const $NETLOGON_REPLICATION_NEEDED = 0x1
Const $NETPROPERTY_PERSISTENT = 1
Const $NETSCAPE_SIGN_CA_CERT_TYPE = 0x1
Const $NETSCAPE_SIGN_CERT_TYPE = 0x10
Const $NETSCAPE_SMIME_CA_CERT_TYPE = 0x2
Const $NETSCAPE_SMIME_CERT_TYPE = 0x20
Const $NETSCAPE_SSL_CA_CERT_TYPE = 0x4
Const $NETSCAPE_SSL_CLIENT_AUTH_CERT_TYPE = 0x80
Const $NETSCAPE_SSL_SERVER_AUTH_CERT_TYPE = 0x40
Const $NETSETUP_ACCT_CREATE = 0x2
Const $NETSETUP_ACCT_DELETE = 0x4
Const $NETSETUP_DOMAIN_JOIN_IF_JOINED = 0x20
Const $NETSETUP_INSTALL_INVOCATION = 0x40000
Const $NETSETUP_JOIN_DOMAIN = 0x1
Const $NETSETUP_JOIN_UNSECURE = 0x40
Const $NETSETUP_MACHINE_PWD_PASSED = 0x80
Const $NETSETUP_WIN9X_UPGRADE = 0x10
Const $NETSH_ARG_DELIMITER = "="
Const $NETSH_CMD_DELIMITER = " "
Const $NETSH_COMMIT = 0
Const $NETSH_COMMIT_STATE = 3
Const $NETSH_ERROR_BASE = 15000
Const $NETSH_ERROR_END = ERROR_SUPPRESS_OUTPUT
Const $NETSH_FLUSH = 2
Const $NETSH_MAX_CMD_TOKEN_LENGTH = 128
Const $NETSH_MAX_TOKEN_LENGTH = 64
Const $NETSH_SAVE = 4
Const $NETSH_UNCOMMIT = 1
Const $NETSH_VERSION_50 = 0x5000
Const $NETWORK_ALIVE_AOL = 0x4
Const $NETWORK_ALIVE_LAN = 0x1
Const $NETWORK_ALIVE_WAN = 0x2
Const $NETWORK_DREP = 0x0
Const $NETWORK_ERROR = 0x4000F105
Const $NETWORK_MESSAGE_BH_ERROR = 3
Const $NETWORK_MESSAGE_NETWORK_ERROR = 4
Const $NETWORK_MESSAGE_RESET_STATE = 2
Const $NETWORK_MESSAGE_TRANSMIT_COMPLETE = 1
Const $NETWORK_MESSAGE_TRIGGER_COMPLETE = 0
Const $NETWORKINFO_FLAGS_LOOPBACK_NOT_SUPPORTED = 0x2
Const $NETWORKINFO_FLAGS_PMODE_NOT_SUPPORTED = 0x1
Const $NETWORKINFO_FLAGS_RAS = 0x20
Const $NETWORKINFO_FLAGS_REMOTE_CARD = 0x10
Const $NETWORKINFO_FLAGS_REMOTE_NAL = 0x4
Const $NETWORKINFO_FLAGS_REMOTE_NAL_CONNECTED = 0x8
Const $NETWORKSTATUS_FLAGS_TRIGGER_PENDING = 0x1
Const $NETWORKSTATUS_STATE_CAPTURING = 3
Const $NETWORKSTATUS_STATE_INIT = 1
Const $NETWORKSTATUS_STATE_PAUSED = 3
Const $NETWORKSTATUS_STATE_READY = 2
Const $NETWORKSTATUS_STATE_VOID = 0
Const $NeverMoved = 0
Const $NeverShown = 0
Const $NEW_OBJ_EID_VERSION = 0x2
Const $NEWFILEOPENORD = 1547
Const $NEWFILEOPENV2ORD = 1552
Const $NEWFRAME = 1
Const $NEWTRANSPARENT = 3
Const $NEXT_PAGE = 0x80
Const $NEXTBAND = 3
Const $NF_QUERY = 3
Const $NF_REQUERY = 4
Const $NFR_ANSI = 1
Const $NFR_UNICODE = 2
Const $NFS_ALL = 0x10
Const $NFS_BUTTON = 0x8
Const $NFS_EDIT = 0x1
Const $NFS_LISTCOMBO = 0x4
Const $NFS_STATIC = 0x2
Const $NFS_USEFONTASSOC = 0x20
Const $NI_CHANGECANDIDATELIST = 0x13
Const $NI_CLOSECANDIDATE = 0x11
Const $NI_COMPOSITIONSTR = 0x15
Const $NI_FINALIZECONVERSIONRESULT = 0x14
Const $NI_IMEMENUSELECTED = 0x18
Const $NI_OPENCANDIDATE = 0x10
Const $NI_SELECTCANDIDATESTR = 0x12
Const $NI_SETCANDIDATE_PAGESIZE = 0x17
Const $NI_SETCANDIDATE_PAGESTART = 0x16
Const $NIF_ICON = 0x2
Const $NIF_INFO = 0x10
Const $NIF_MESSAGE = 0x1
Const $NIF_STATE = 0x8
Const $NIF_TIP = 0x4
Const $NIIF_ERROR = 0x3
Const $NIIF_INFO = 0x1
Const $NIIF_NONE = 0x0
Const $NIIF_WARNING = 0x2
Const $NIM_ADD = 0x0
Const $NIM_DELETE = 0x2
Const $NIM_MODIFY = 0x1
Const $NIM_SETFOCUS = 0x3
Const $NIM_SETVERSION = 0x4
Const $NIN_GETVERSION = $WM_USER + 0
Const $NIN_KEYSELECT = BitOR($NIN_SELECT, $NINF_KEY)
Const $NIN_SELECT = $WM_USER + 0x2
Const $NINF_KEY = 0x1
Const $NIS_HIDDEN = 0x1
Const $NIS_SHAREDICON = 0x2
Const $NLADMIN_E_DUPLICATE_CATALOG = 0x80041901
Const $NLADMIN_E_FAILED_TO_GIVE_ACCOUNT_PRIVILEGE = 0x80041903
Const $NLADMIN_S_NOT_ALL_BUILD_CATALOGS_INITIALIZED = 0x41902
Const $NLS_ALPHANUMERIC = 0x0
Const $NLS_DBCSCHAR = 0x10000
Const $NLS_HIRAGANA = 0x40000
Const $NLS_IME_CONVERSION = 0x800000
Const $NLS_IME_DISABLE = 0x20000000
Const $NLS_KATAKANA = 0x20000
Const $NLS_ROMAN = 0x400000
Const $NLS_VALID_LOCALE_MASK = 0xFFFFf
Const $NM_ACCESS_CATEGORY = 0x1000C
Const $NM_ACTIVATION_SCHEDULE = 0x25581
Const $NM_ACTIVATION_STYLE = 0x10049
Const $NM_ADDRESS = 0x20082
Const $NM_ADDRESS_ENTRY_DISPLAY_TABLE = 0x24482
Const $NM_ADDRESS_ENTRY_DISPLAY_TABLE_MSDOS = 0x21083
Const $NM_ADDRESS_SYNTAX = 0x27F81
Const $NM_ADDRESS_TYPE = 0x25E82
Const $NM_ADMD = 0x26881
Const $NM_ADMIN_DESCRIPTION = 0x26281
Const $NM_ADMIN_DISPLAY_NAME = 0x24281
Const $NM_ADMIN_EXTENSION_DLL = 0x1005F
Const $NM_ALIASED_OBJECT_NAME = 0x10001
Const $NM_ALT_RECIPIENT = 0x1007E
Const $NM_ALT_RECIPIENT_BL = 0x22682
Const $NM_ANCESTOR_ID = 0x20582
Const $NM_APPLET_KEY = "SOFTWARE\\Microsoft\\Conferencing\\T.120 Applets"
Const $NM_ASSISTANT_NAME = 0x23C83
Const $NM_ASSOC_NT_ACCOUNT = 0x25481
Const $NM_ASSOC_REMOTE_DXA = 0x22B82
Const $NM_ASSOCIATION_LIFETIME = 0x21581
Const $NM_ATTRIBUTE_ID = 0x1001E
Const $NM_ATTRIBUTE_SYNTAX = 0x10020
Const $NM_AUTH_ORIG = 0x20181
Const $NM_AUTH_ORIG_BL = 0x22282
Const $NM_AUTHORITY_REVOC_LIST = 0x10026
Const $NM_AUTHORIZED_DOMAIN = 0x24A81
Const $NM_AUTHORIZED_PASSWORD = 0x24181
Const $NM_AUTHORIZED_USER = 0x21482
Const $NM_AUTOREPLY = 0x21E82
Const $NM_AUTOREPLY_MESSAGE = 0x21F82
Const $NM_AUTOREPLY_SUBJECT = 0x23A83
Const $NM_AUXILIARY_CLASS = 0x25F82
Const $NM_BRIDGEHEAD_SERVERS = 0x24F83
Const $NM_BUSINESS_CATEGORY = 0x1000F
Const $NM_BUSINESS_ROLES = 0x10069
Const $NM_CA_CERT = 0x10025
Const $NM_CACHEHINT = $NMLVCACHEHINT
Const $NM_CAN_CREATE_PF = 0x1000B
Const $NM_CAN_CREATE_PF_BL = 0x25382
Const $NM_CAN_CREATE_PF_DL = 0x1003E
Const $NM_CAN_CREATE_PF_DL_BL = 0x25482
Const $NM_CAN_NOT_CREATE_PF = 0x1003F
Const $NM_CAN_NOT_CREATE_PF_BL = 0x25582
Const $NM_CAN_NOT_CREATE_PF_DL = 0x22C82
Const $NM_CAN_NOT_CREATE_PF_DL_BL = 0x25682
Const $NM_CAN_PRESERVE_DNS = 0x24783
Const $NM_CERT_REVOC_LIST = 0x10027
Const $NM_CHAR = $NM_FIRST - 18
Const $NM_CLICK = $NM_FIRST - 2
Const $NM_CLOCK_ALERT_OFFSET = 0x22581
Const $NM_CLOCK_ALERT_REPAIR = 0x22481
Const $NM_CLOCK_WARNING_OFFSET = 0x23181
Const $NM_CLOCK_WARNING_REPAIR = 0x22681
Const $NM_COMMENT = 0x10051
Const $NM_COMMON_NAME = 0x10003
Const $NM_COMPANY = 0x21281
Const $NM_COMPUTER_NAME = 0x10014
Const $NM_CONNECTED_DOMAINS = 0x25381
Const $NM_CONTAINER_INFO = 0x22882
Const $NM_COST = 0x20781
Const $NM_COUNTRY_NAME = 0x10006
Const $NM_CROSS_CERT_PAIR = 0x10028
Const $NM_CUSTOMDRAW = $NM_FIRST - 12
Const $NM_DBLCLK = $NM_FIRST - 3
Const $NM_DELIV_CONT_LENGTH = 0x20A81
Const $NM_DELIV_EITS = 0x20B81
Const $NM_DELIV_EXT_CONT_TYPES = 0x20C81
Const $NM_DELIVER_AND_REDIRECT = 0x23E81
Const $NM_DELIVERY_MECHANISM = 0x27181
Const $NM_DEPARTMENT = 0x20D81
Const $NM_DESCRIPTION = 0x1000D
Const $NM_DEST_INDICATOR = 0x1001B
Const $NM_DIAGNOSTIC_REG_KEY = 0x23D81
Const $NM_DISPLAY_NAME = 0x1000D
Const $NM_DISPLAY_NAME_OVERRIDE = 0x24082
Const $NM_DISPLAY_NAME_PRINTABLE = 0x26182
Const $NM_DL_MEM_REJECT_PERMS = 0x1002F
Const $NM_DL_MEM_REJECT_PERMS_BL = 0x22582
Const $NM_DL_MEM_SUBMIT_PERMS = 0x21081
Const $NM_DL_MEM_SUBMIT_PERMS_BL = 0x22382
Const $NM_DL_MEMBER_RULE = 0x24A82
Const $NM_DMD_LOCATION = 0x10024
Const $NM_DOMAIN_DEF_ALT_RECIP = 0x21181
Const $NM_DOMAIN_NAME = 0x21381
Const $NM_DSA_SIGNATURE = 0x1004A
Const $NM_DXA_ADMIN_COPY = 0x27A82
Const $NM_DXA_ADMIN_FORWARD = 0x27B82
Const $NM_DXA_ADMIN_UPDATE = 0x27D82
Const $NM_DXA_APPEND_REQCN = 0x22E81
Const $NM_DXA_CONF_CONTAINER_LIST = 0x23481
Const $NM_DXA_CONF_REQ_TIME = 0x1007A
Const $NM_DXA_CONF_SEQ = 0x23881
Const $NM_DXA_CONF_SEQ_USN = 0x1002D
Const $NM_DXA_EXCHANGE_OPTIONS = 0x26782
Const $NM_DXA_EXPORT_NOW = 0x27982
Const $NM_DXA_FLAGS = 0x1006A
Const $NM_DXA_IMP_SEQ = 0x10074
Const $NM_DXA_IMP_SEQ_TIME = 0x10075
Const $NM_DXA_IMP_SEQ_USN = 0x10056
Const $NM_DXA_IMPORT_NOW = 0x27882
Const $NM_DXA_IN_TEMPLATE_MAP = 0x26B82
Const $NM_DXA_LOCAL_ADMIN = 0x10071
Const $NM_DXA_LOGGING_LEVEL = 0x27E82
Const $NM_DXA_NATIVE_ADDRESS_TYPE = 0x24B82
Const $NM_DXA_OUT_TEMPLATE_MAP = 0x26C82
Const $NM_DXA_PASSWORD = 0x23182
Const $NM_DXA_PREV_EXCHANGE_OPTIONS = 0x25881
Const $NM_DXA_PREV_EXPORT_NATIVE_ONLY = 0x24B81
Const $NM_DXA_PREV_IN_EXCHANGE_SENSITIVITY = 0x1005A
Const $NM_DXA_PREV_REMOTE_ENTRIES = 0x20982
Const $NM_DXA_PREV_REPLICATION_SENSITIVITY = 0x25781
Const $NM_DXA_PREV_TEMPLATE_OPTIONS = 0x20B83
Const $NM_DXA_PREV_TYPES = 0x25981
Const $NM_DXA_RECIPIENT_CP = 0x20083
Const $NM_DXA_REMOTE_CLIENT = 0x10070
Const $NM_DXA_REQ_SEQ = 0x10065
Const $NM_DXA_REQ_SEQ_TIME = 0x10072
Const $NM_DXA_REQ_SEQ_USN = 0x23681
Const $NM_DXA_REQNAME = 0x23E83
Const $NM_DXA_SVR_SEQ = 0x26882
Const $NM_DXA_SVR_SEQ_TIME = 0x26982
Const $NM_DXA_SVR_SEQ_USN = 0x1007C
Const $NM_DXA_TASK = 0x10064
Const $NM_DXA_TEMPLATE_OPTIONS = 0x26682
Const $NM_DXA_TEMPLATE_TIMESTAMP = 0x26D82
Const $NM_DXA_TYPES = 0x10077
Const $NM_DXA_UNCONF_CONTAINER_LIST = 0x23581
Const $NM_ENABLED_PROTOCOLS = 0x25A83
Const $NM_ENCAPSULATION_METHOD = 0x24083
Const $NM_ENCRYPT = 0x26C81
Const $NM_ENCRYPT_ALG_LIST_NA = 0x20281
Const $NM_ENCRYPT_ALG_LIST_OTHER = 0x20F83
Const $NM_ENCRYPT_ALG_SELECTED_NA = 0x21183
Const $NM_ENCRYPT_ALG_SELECTED_OTHER = 0x20D83
Const $NM_ENV_CONF_ID = "_conf_id"
Const $NM_ENV_NODE_ID = "_node_id"
Const $NM_EXPAND_DLS_LOCALLY = 0x24981
Const $NM_EXPIRATION_TIME = 0x20A83
Const $NM_EXPORT_CONTAINERS = 0x1006F
Const $NM_EXPORT_CUSTOM_RECIPIENTS = 0x23382
Const $NM_EXTENDED_CHARS_ALLOWED = 0x27C82
Const $NM_EXTENSION_ATTRIBUTE_1 = 0x22783
Const $NM_EXTENSION_ATTRIBUTE_10 = 0x23083
Const $NM_EXTENSION_ATTRIBUTE_2 = 0x22883
Const $NM_EXTENSION_ATTRIBUTE_3 = 0x22983
Const $NM_EXTENSION_ATTRIBUTE_4 = 0x22A83
Const $NM_EXTENSION_ATTRIBUTE_5 = 0x22B83
Const $NM_EXTENSION_ATTRIBUTE_6 = 0x22C83
Const $NM_EXTENSION_ATTRIBUTE_7 = 0x22D83
Const $NM_EXTENSION_ATTRIBUTE_8 = 0x22E83
Const $NM_EXTENSION_ATTRIBUTE_9 = 0x22F83
Const $NM_EXTENSION_DATA = 0x26481
Const $NM_EXTENSION_NAME = 0x26381
Const $NM_EXTENSION_NAME_INHERITED = 0x10061
Const $NM_FACSIMILE_PHONE_NBR = 0x10017
Const $NM_FILE_VERSION = 0x23281
Const $NM_FILTER_LOCAL_ADDRESSES = 0x1002C
Const $NM_FIRST = 0
Const $NM_FOLDER_PATHNAME = 0x25182
Const $NM_FOLDERS_CONTAINER = 0x26B81
Const $NM_FOREIGN_DSAS = 0x10044
Const $NM_GARBAGE_COLL_PERIOD = 0x22D82
Const $NM_GATEWAY_LOCAL_CRED = 0x10025
Const $NM_GATEWAY_LOCAL_DESIG = 0x1001D
Const $NM_GATEWAY_PROXY = 0x22E82
Const $NM_GATEWAY_ROUTING_TREE = 0x22781
Const $NM_GIVEN_NAME = 0x10029
Const $NM_GOVERNS_ID = 0x10016
Const $NM_GWART_LAST_MODIFIED = 0x20482
Const $NM_HAS_FULL_REPLICA_NCS = 0x1000F
Const $NM_HAS_MASTER_NCS = 0x1000E
Const $NM_HELP_DATA16 = 0x21283
Const $NM_HELP_DATA32 = 0x10009
Const $NM_HELP_FILE_NAME = 0x24782
Const $NM_HEURISTICS = 0x24483
Const $NM_HIDE_DL_MEMBERSHIP = 0x22982
Const $NM_HIDE_FROM_ADDRESS_BOOK = 0x22981
Const $NM_HOME_MDB = 0x27481
Const $NM_HOME_MDB_BL = 0x20983
Const $NM_HOME_MTA = 0x22B81
Const $NM_HOME_PUBLIC_SERVER = 0x23983
Const $NM_HOVER = $NM_FIRST - 13
Const $NM_IMPORT_CONTAINER = 0x1006E
Const $NM_IMPORT_SENSITIVITY = 0x27F82
Const $NM_IMPORTED_FROM = 0x20782
Const $NM_INBOUND_SITES = 0x10047
Const $NM_INITIALS = 0x20E83
Const $NM_INSTANCE_TYPE = 0x10001
Const $NM_INTERNAT_ISDN_NBR = 0x10019
Const $NM_INVOCATION_ID = 0x10073
Const $NM_IS_DELETED = 0x10030
Const $NM_IS_MEMBER_OF_DL = 0x10066
Const $NM_IS_SINGLE_VALUED = 0x10021
Const $NM_KCC_STATUS = 0x26D81
Const $NM_KEYDOWN = $NM_FIRST - 15
Const $NM_KILLFOCUS = $NM_FIRST - 8
Const $NM_KM_SERVER = 0x23883
Const $NM_KNOWLEDGE_INFO = 0x10002
Const $NM_LANGUAGE = 0x25383
Const $NM_LAST = -99
Const $NM_LDAP_DISPLAY_NAME = 0x24C83
Const $NM_LDOWN = $NM_FIRST - 20
Const $NM_LINE_WRAP = 0x24183
Const $NM_LINK_ID = 0x10032
Const $NM_LOCAL_BRIDGE_HEAD = 0x23782
Const $NM_LOCAL_BRIDGE_HEAD_ADDRESS = 0x26181
Const $NM_LOCAL_INITIAL_TURN = 0x10027
Const $NM_LOCAL_SCOPE = 0x10011
Const $NM_LOCALITY_NAME = 0x10007
Const $NM_LOG_FILENAME = 0x24081
Const $NM_LOG_ROLLOVER_INTERVAL = 0x25C82
Const $NM_MAIL_NICKNAME = 0x23F83
Const $NM_MAINTAIN_AUTOREPLY_HISTORY = 0x25181
Const $NM_MANAGER = 0x24F82
Const $NM_MAPI_DISPLAY_TYPE = 0x10037
Const $NM_MAPI_ID = 0x10031
Const $NM_MAPI_RECIPIENT = 0x27382
Const $NM_MASTER_DSA = 0x10006
Const $NM_MAXIMUM_OBJECT_ID = 0x24A83
Const $NM_MAY_CONTAIN = 0x10019
Const $NM_MDB_BACKOFF_INTERVAL = 0x10048
Const $NM_MDB_MSG_TIME_OUT_PERIOD = 0x10040
Const $NM_MDB_OVER_QUOTA_LIMIT = 0x21082
Const $NM_MDB_STORAGE_QUOTA = 0x20A82
Const $NM_MDB_UNREAD_LIMIT = 0x10045
Const $NM_MDB_USE_DEFAULTS = 0x23582
Const $NM_MEMBER = 0x1001F
Const $NM_MESSAGE_TRACKING_ENABLED = 0x24583
Const $NM_MONITOR_CLOCK = 0x22381
Const $NM_MONITOR_SERVERS = 0x21C81
Const $NM_MONITOR_SERVICES = 0x22081
Const $NM_MONITORED_CONFIGURATIONS = 0x24681
Const $NM_MONITORED_SERVERS = 0x23381
Const $NM_MONITORED_SERVICES = 0x24781
Const $NM_MONITORING_ALERT_DELAY = 0x21E81
Const $NM_MONITORING_ALERT_UNITS = 0x10039
Const $NM_MONITORING_AVAILABILITY_STYLE = 0x24283
Const $NM_MONITORING_AVAILABILITY_WINDOW = 0x24881
Const $NM_MONITORING_CACHED_VIA_MAIL = 0x24481
Const $NM_MONITORING_CACHED_VIA_RPC = 0x24581
Const $NM_MONITORING_ESCALATION_PROCEDURE = 0x23C81
Const $NM_MONITORING_HOTSITE_POLL_INTERVAL = 0x23A81
Const $NM_MONITORING_HOTSITE_POLL_UNITS = 0x10057
Const $NM_MONITORING_MAIL_UPDATE_INTERVAL = 0x24381
Const $NM_MONITORING_MAIL_UPDATE_UNITS = 0x1005D
Const $NM_MONITORING_NORMAL_POLL_INTERVAL = 0x23B81
Const $NM_MONITORING_NORMAL_POLL_UNITS = 0x10058
Const $NM_MONITORING_RECIPIENTS = 0x21F81
Const $NM_MONITORING_RECIPIENTS_NDR = 0x20383
Const $NM_MONITORING_RPC_UPDATE_INTERVAL = 0x1005C
Const $NM_MONITORING_RPC_UPDATE_UNITS = 0x10059
Const $NM_MONITORING_WARNING_DELAY = 0x21D81
Const $NM_MONITORING_WARNING_UNITS = 0x10038
Const $NM_MTA_LOCAL_CRED = 0x20E82
Const $NM_MTA_LOCAL_DESIG = 0x20F82
Const $NM_MUST_CONTAIN = 0x10018
Const $NM_N_ADDRESS = 0x21A82
Const $NM_N_ADDRESS_TYPE = 0x25E81
Const $NM_NCHITTEST = $NM_FIRST - 14
Const $NM_NETWORK_ADDRESS = 0x24B83
Const $NM_NNTP_CHARACTER_SET = 0x25883
Const $NM_NNTP_CONTENT_FORMAT = 0x25183
Const $NM_NONSTD_KEY_TYPE = "NonStd Key"
Const $NM_NT_MACHINE_NAME = 0x24683
Const $NM_NT_SECURITY_DESCRIPTOR = 0x21982
Const $NM_NUM_OF_OPEN_RETRIES = 0x21481
Const $NM_NUM_OF_TRANSFER_RETRIES = 0x20681
Const $NM_OBJ_DIST_NAME = 0x10033
Const $NM_OBJECT_CLASS = 0x10000
Const $NM_OBJECT_CLASS_CATEGORY = 0x27282
Const $NM_OBJECT_VERSION = 0x1004C
Const $NM_OFF_LINE_AB_CONTAINERS = 0x20783
Const $NM_OFF_LINE_AB_SCHEDULE = 0x20583
Const $NM_OFF_LINE_AB_SERVER = 0x20883
Const $NM_OFF_LINE_AB_STYLE = 0x20683
Const $NM_OID_TYPE = 0x24282
Const $NM_OM_OBJECT_CLASS = 0x25A81
Const $NM_OM_SYNTAX = 0x26781
Const $NM_OOF_REPLY_TO_ORIGINATOR = 0x23683
Const $NM_OPEN_RETRY_INTERVAL = 0x20F81
Const $NM_ORG_NAME = 0x1000A
Const $NM_ORG_UNIT_NAME = 0x1000B
Const $NM_ORIGINAL_DISPLAY_TABLE = 0x23D83
Const $NM_ORIGINAL_DISPLAY_TABLE_MSDOS = 0x25681
Const $NM_OUTBOUND_SITES = 0x10000
Const $NM_OUTOFMEMORY = $NM_FIRST - 1
Const $NM_OWNER = 0x10020
Const $NM_OWNER_BL = 0x10068
Const $NM_P_SELECTOR = 0x21D82
Const $NM_P_SELECTOR_INBOUND = 0x10034
Const $NM_PER_MSG_DIALOG_DISPLAY_TABLE = 0x24582
Const $NM_PER_RECIP_DIALOG_DISPLAY_TABLE = 0x24682
Const $NM_PERIOD_REP_SYNC_TIMES = 0x20C82
Const $NM_PERIOD_REPL_STAGGER = 0x20882
Const $NM_PF_CONTACTS = 0x1004B
Const $NM_PHONE_NBR = 0x10014
Const $NM_PHYS_DELIV_OFF_NAME = 0x10013
Const $NM_POP_CHARACTER_SET = 0x25483
Const $NM_POP_CONTENT_FORMAT = 0x25283
Const $NM_POSS_SUPERIORS = 0x10008
Const $NM_POST_OFFICE_BOX = 0x10012
Const $NM_POSTAL_ADDRESS = 0x10010
Const $NM_POSTAL_CODE = 0x10011
Const $NM_PREF_DELIV_METHOD = 0x1001C
Const $NM_PRESENTATION_ADDRESS = 0x1001D
Const $NM_PRMD = 0x26081
Const $NM_PROXY_ADDRESSES = 0x25281
Const $NM_PROXY_GENERATOR_DLL = 0x24882
Const $NM_PUBLIC_DELEGATES = 0x26E81
Const $NM_PUBLIC_DELEGATES_BL = 0x22782
Const $NM_QUOTA_NOTIFICATION_SCHEDULE = 0x10062
Const $NM_QUOTA_NOTIFICATION_STYLE = 0x20483
Const $NM_RANGE_LOWER = 0x10022
Const $NM_RANGE_UPPER = 0x10023
Const $NM_RAS_CALLBACK_NUMBER = 0x23B82
Const $NM_RAS_PHONE_NUMBER = 0x23A82
Const $NM_RAS_PHONEBOOK_ENTRY_NAME = 0x23982
Const $NM_RAS_REMOTE_SRVR_NAME = 0x1004E
Const $NM_RCLICK = $NM_FIRST - 5
Const $NM_RDBLCLK = $NM_FIRST - 6
Const $NM_RDN_ATT_ID = 0x1001A
Const $NM_RDOWN = $NM_FIRST - 21
Const $NM_REF_FULL_REPLICAS = 0x10041
Const $NM_REF_MASTER_DSA = 0x10042
Const $NM_REGISTERED_ADDRESS = 0x1001A
Const $NM_REGVAL_APP_PATH = "Path"
Const $NM_REGVAL_CMD_LINE = "CmdLine"
Const $NM_REGVAL_CURR_DIR = "Directory"
Const $NM_REGVAL_DESCRIPTION = "Description"
Const $NM_REGVAL_MANUFACTURER = "Manufacturer"
Const $NM_REGVAL_PRODUCT_NAME = "ProductName"
Const $NM_RELEASEDCAPTURE = $NM_FIRST - 16
Const $NM_REMOTE_BRIDGE_HEAD = 0x23F81
Const $NM_REMOTE_BRIDGE_HEAD_ADDRESS = 0x1005E
Const $NM_REMOTE_OUT_BH_SERVER = 0x23682
Const $NM_REMOTE_SITE = 0x1001B
Const $NM_REPLICATION_MAIL_MSG_SIZE = 0x10067
Const $NM_REPLICATION_SENSITIVITY = 0x25F81
Const $NM_REPLICATION_STAGGER = 0x25D82
Const $NM_REPORT_TO_ORIGINATOR = 0x24E81
Const $NM_REPORT_TO_OWNER = 0x24F81
Const $NM_REPORTS = 0x23483
Const $NM_REPS_FROM = 0x1005B
Const $NM_REPS_TO = 0x10053
Const $NM_REPS_TO_EXT = 0x1002B
Const $NM_REQ_SEQ = 0x22D81
Const $NM_RESPONSIBLE_LOCAL_DXA = 0x22A82
Const $NM_RETURN = $NM_FIRST - 4
Const $NM_RID_SERVER = 0x25A82
Const $NM_ROLE_OCCUPANT = 0x10021
Const $NM_ROUTING_LIST = 0x26282
Const $NM_RTS_CHECKPOINT_SIZE = 0x21881
Const $NM_RTS_RECOVERY_TIMEOUT = 0x21781
Const $NM_RTS_WINDOW_SIZE = 0x21981
Const $NM_RUNS_ON = 0x23981
Const $NM_S_SELECTOR = 0x21C82
Const $NM_S_SELECTOR_INBOUND = 0x1002E
Const $NM_SCHEMA_FLAGS = 0x24E83
Const $NM_SCHEMA_VERSION = 0x25783
Const $NM_SEARCH_FLAGS = 0x24E82
Const $NM_SEARCH_GUIDE = 0x1000E
Const $NM_SECURITY_PROTOCOL = 0x10052
Const $NM_SEE_ALSO = 0x10022
Const $NM_SERIAL_NBR = 0x10005
Const $NM_SERVICE_ACTION_FIRST = 0x22181
Const $NM_SERVICE_ACTION_OTHER = 0x1003B
Const $NM_SERVICE_ACTION_SECOND = 0x1003C
Const $NM_SERVICE_RESTART_DELAY = 0x22281
Const $NM_SERVICE_RESTART_MESSAGE = 0x1003A
Const $NM_SESSION_DISCONNECT_TIMER = 0x21A81
Const $NM_SETCURSOR = $NM_FIRST - 17
Const $NM_SETFOCUS = $NM_FIRST - 7
Const $NM_SITE_AFFINITY = 0x23283
Const $NM_SITE_FOLDER_GUID = 0x24883
Const $NM_SITE_FOLDER_SERVER = 0x24983
Const $NM_SITE_PROXY_SPACE = 0x20183
Const $NM_SPACE_LAST_COMPUTED = 0x20283
Const $NM_STATE_OR_PROV_NAME = 0x10008
Const $NM_STD_KEY_TYPE = "Object Key"
Const $NM_STREET_ADDRESS = 0x10009
Const $NM_SUB_CLASS_OF = 0x10015
Const $NM_SUB_REFS = 0x10007
Const $NM_SUB_SITE = 0x25683
Const $NM_SUBMISSION_CONT_LENGTH = 0x21882
Const $NM_SUPPORT_APPL_CONTEXT = 0x1001E
Const $NM_SUPPORTING_STACK = 0x1001C
Const $NM_SUPPORTING_STACK_BL = 0x26582
Const $NM_SURNAME = 0x10004
Const $NM_T_SELECTOR = 0x21B82
Const $NM_T_SELECTOR_INBOUND = 0x10005
Const $NM_TARGET_ADDRESS = 0x26082
Const $NM_TARGET_MTAS = 0x20382
Const $NM_TELEPHONE_ASSISTANT = 0x1004F
Const $NM_TELEPHONE_FAX = 0x1002A
Const $NM_TELEPHONE_HOME = 0x1004D
Const $NM_TELEPHONE_HOME2 = 0x21582
Const $NM_TELEPHONE_MOBILE = 0x10004
Const $NM_TELEPHONE_OFFICE1 = 0x10076
Const $NM_TELEPHONE_OFFICE2 = 0x10012
Const $NM_TELEPHONE_PAGER = 0x20682
Const $NM_TELETEX_TERM_IDENT = 0x10016
Const $NM_TELEX_NBR = 0x10015
Const $NM_TEMP_ASSOC_THRESHOLD = 0x24982
Const $NM_TEXT_COUNTRY = 0x20381
Const $NM_THEMECHANGED = $NM_FIRST - 22
Const $NM_TITLE = 0x1000C
Const $NM_TOMBSTONE_LIFETIME = 0x10036
Const $NM_TOOLTIPSCREATED = $NM_FIRST - 19
Const $NM_TRACKING_LOG_PATH_NAME = 0x25B82
Const $NM_TRANS_RETRY_MINS = 0x25B81
Const $NM_TRANS_TIMEOUT_MINS = 0x25C81
Const $NM_TRANSFER_RETRY_INTERVAL = 0x20581
Const $NM_TRANSFER_TIMEOUT_NON_URGENT = 0x20881
Const $NM_TRANSFER_TIMEOUT_NORMAL = 0x20981
Const $NM_TRANSFER_TIMEOUT_URGENT = 0x20E81
Const $NM_TRANSLATION_TABLE_USED = 0x20C83
Const $NM_TRANSPORT_EXPEDITED_DATA = 0x21681
Const $NM_TRUST_LEVEL = 0x10046
Const $NM_TURN_REQUEST_THRESHOLD = 0x10026
Const $NM_TWO_WAY_ALTERNATE_FACILITY = 0x10028
Const $NM_UNAUTH_ORIG = 0x25D81
Const $NM_UNAUTH_ORIG_BL = 0x22482
Const $NM_USE_SERVER_VALUES = 0x25983
Const $NM_USER_CERT = 0x10024
Const $NM_USER_PASSWORD = 0x10023
Const $NM_USN_CHANGED = 0x10078
Const $NM_USN_CREATED = 0x10013
Const $NM_USN_DSA_LAST_OBJ_REMOVED = 0x20B82
Const $NM_USN_INTERSITE = 0x25583
Const $NM_USN_LAST_OBJ_REM = 0x10079
Const $NM_USN_SOURCE = 0x27682
Const $NM_WHEN_CHANGED = 0x10003
Const $NM_WHEN_CREATED = 0x10002
Const $NM_WWW_HOME_PAGE = 0x25083
Const $NM_X121_ADDRESS = 0x10018
Const $NM_X25_CALL_USER_DATA_INCOMING = 0x23C82
Const $NM_X25_CALL_USER_DATA_OUTGOING = 0x23D82
Const $NM_X25_FACILITIES_DATA_INCOMING = 0x23E82
Const $NM_X25_FACILITIES_DATA_OUTGOING = 0x23F82
Const $NM_X25_LEASED_LINE_PORT = 0x24182
Const $NM_X25_LEASED_OR_SWITCHED = 0x27482
Const $NM_X25_REMOTE_MTA_PHONE = 0x27582
Const $NM_X400_ATTACHMENT_TYPE = 0x10063
Const $NM_X400_SELECTOR_SYNTAX = 0x23B83
Const $NM_X500_ACCESS_CONTROL_LIST = 0x23183
Const $NM_X509_CERT = 0x24D83
Const $NM_XMIT_TIMEOUT_NON_URGENT = 0x10054
Const $NM_XMIT_TIMEOUT_NORMAL = 0x10043
Const $NM_XMIT_TIMEOUT_URGENT = 0x10035
Const $nMaxOrgUnits = 4
Const $NMERR_ACCESS_DENIED = 74
Const $NMERR_ADDRESS_ALREADY_EXISTS = 10
Const $NMERR_ADDRESS_NOT_FOUND = 29
Const $NMERR_AGENT_IN_USE = 95
Const $NMERR_ALREADY_CONNECTED = 103
Const $NMERR_AMBIGUOUS_SPECIFIER = 1005
Const $NMERR_BAD_VERSION = 137
Const $NMERR_BLOB_CATEGORY_NOT_FOUND = 1007
Const $NMERR_BLOB_CONVERSION_ERROR = 1010
Const $NMERR_BLOB_ENTRY_ALREADY_EXISTS = 1003
Const $NMERR_BLOB_ENTRY_DOES_NOT_EXIST = 1004
Const $NMERR_BLOB_NOT_INITIALIZED = 1000
Const $NMERR_BLOB_OWNER_NOT_FOUND = 1006
Const $NMERR_BLOB_STRING_INVALID = 1012
Const $NMERR_BUFFER_TOO_SMALL = 6
Const $NMERR_BUFFERS_ALREADY_EXIST = 22
Const $NMERR_CANCEL_SAVE_CAPTURE = 92
Const $NMERR_CAPTURE_NOT_PAUSED = 66
Const $NMERR_CAPTURE_PAUSED = 20
Const $NMERR_CAPTURING = 3
Const $NMERR_CLASS_NOT_REGISTERED = 1015
Const $NMERR_CONFIGURATION_REQUIRED = 2013
Const $NMERR_COULD_NOT_CREATE_DIRECTORY = 115
Const $NMERR_COULD_NOT_CREATE_TEMPFILE = 40
Const $NMERR_DELAYED = 105
Const $NMERR_DISCARD_FRAME = 91
Const $NMERR_DISCONNECTED = 97
Const $NMERR_DISK_NOT_LOCAL_FIXED = 114
Const $NMERR_DRIVER_NOT_FOUND = 9
Const $NMERR_ESP = 138
Const $NMERR_EXPERT_ALREADY_IN_GROUP = 133
Const $NMERR_EXPERT_NOT_IN_GROUP = 134
Const $NMERR_EXPERT_REPORT_FAILED = 119
Const $NMERR_EXPERT_TERMINATE = 125
Const $NMERR_FILE_ALREADY_EXISTS = 8
Const $NMERR_FILE_NOT_FOUND = 18
Const $NMERR_FILE_READ_ERROR = 77
Const $NMERR_FILE_WRITE_ERROR = 78
Const $NMERR_FILTER_INVALID_EXPRESSION = 57
Const $NMERR_FRAME_ALREADY_HAS_CAPTURE = 88
Const $NMERR_FRAME_FAILED_FILTER = 124
Const $NMERR_FRAME_HAS_NO_CAPTURE = 87
Const $NMERR_FRAME_NOT_FOUND = 51
Const $NMERR_FRAME_NOT_RECOGNIZED = 7
Const $NMERR_GROUP_NAME_ALREADY_EXISTS = 131
Const $NMERR_ILLEGAL_TRIGGER = 1011
Const $NMERR_INTERNAL_EXCEPTION = 69
Const $NMERR_INVALID_BLOB = 1001
Const $NMERR_INVALID_DATA = 60
Const $NMERR_INVALID_EXPERT_GROUP = 128
Const $NMERR_INVALID_EXPERT_HANDLE = 130
Const $NMERR_INVALID_EXPERT_NAME = 129
Const $NMERR_INVALID_FILE_FORMAT = 39
Const $NMERR_INVALID_FRAMESPROC = 100
Const $NMERR_INVALID_GROUP_NAME = 132
Const $NMERR_INVALID_GROUP_ROOT = 136
Const $NMERR_INVALID_HADDRESSDB = 28
Const $NMERR_INVALID_HBUFFER = 59
Const $NMERR_INVALID_HCAPTURE = 55
Const $NMERR_INVALID_HFILTER = 2
Const $NMERR_INVALID_HFRAME = 11
Const $NMERR_INVALID_HNETWORK = 48
Const $NMERR_INVALID_HPASSWORD = 75
Const $NMERR_INVALID_HPROPERTY = 13
Const $NMERR_INVALID_HPROPERTYDB = 33
Const $NMERR_INVALID_HPROTOCOL = 12
Const $NMERR_INVALID_INDEX = 2006
Const $NMERR_INVALID_LIST_INDEX = 2000
Const $NMERR_INVALID_MEDIA_TYPE = 94
Const $NMERR_INVALID_MONITOR = 2001
Const $NMERR_INVALID_MONITOR_CONFIG = 2005
Const $NMERR_INVALID_MONITOR_DLL = 2002
Const $NMERR_INVALID_NETWORK_ID = 54
Const $NMERR_INVALID_PACKET_LENGTH = 67
Const $NMERR_INVALID_PARAMETER = 76
Const $NMERR_INVALID_PARSER_DLL = 36
Const $NMERR_INVALID_REGISTRY_CONFIGURATION = 104
Const $NMERR_INVALID_REMOTE_COMPUTERNAME = 1016
Const $NMERR_IP_ADDRESS_NOT_FOUND = 80
Const $NMERR_LOAD_EXPERT_FAILED = 118
Const $NMERR_LOAD_PARSER_FAILED = 26
Const $NMERR_LOCK_NESTING_TOO_DEEP = 25
Const $NMERR_LOCKED = 14
Const $NMERR_LOCKED_FRAMES = 82
Const $NMERR_LOST_CONNECTION = 93
Const $NMERR_MAC_DRIVER_OPEN_FAILURE = 71
Const $NMERR_MCS_IS_BUSY = 2010
Const $NMERR_MEMORY_MAPPED_FILE_ERROR = 1
Const $NMERR_MONITOR_CONFIG_FAILED = 2016
Const $NMERR_MONITOR_CONNECT_FAILED = 2021
Const $NMERR_MONITOR_ENABLED = 2007
Const $NMERR_MONITOR_FAULTED = 2018
Const $NMERR_MONITOR_INIT_FAILED = 2017
Const $NMERR_MONITOR_IS_BUSY = 2009
Const $NMERR_MONITOR_NOT_CONFIGURED = 2015
Const $NMERR_MONITOR_NOT_CONNECTED = 2014
Const $NMERR_MONITOR_NOT_RUNNING = 2008
Const $NMERR_MONITOR_START_FAILED = 2022
Const $NMERR_MONITOR_STOP_FAILED = 2023
Const $NMERR_MSDOS_DRIVER_INIT_FAILURE = 63
Const $NMERR_MSDOS_DRIVER_NOT_LOADED = 61
Const $NMERR_NAL_IS_NOT_REMOTE = 89
Const $NMERR_NETWORK_ALREADY_OPENED = 49
Const $NMERR_NETWORK_BUSY = 65
Const $NMERR_NETWORK_ERROR = 99
Const $NMERR_NETWORK_NOT_OPENED = 50
Const $NMERR_NETWORK_NOT_PRESENT = 30
Const $NMERR_NO_ATTACHED_PROPERTIES = 37
Const $NMERR_NO_BUFFERS = 21
Const $NMERR_NO_CONVERSATION_STATS = 122
Const $NMERR_NO_DEFAULT_CAPTURE_DIRECTORY = 116
Const $NMERR_NO_DLLS_FOUND = 121
Const $NMERR_NO_FRAME_NUMBER = 86
Const $NMERR_NO_FRAMES = 38
Const $NMERR_NO_HANDLES = 53
Const $NMERR_NO_INPUT_BLOBS = 3019
Const $NMERR_NO_MATCHING_NPPS = 3017
Const $NMERR_NO_MONITORS = 2011
Const $NMERR_NO_MORE_FRAMES = 5
Const $NMERR_NO_NPP_DLLS = 3020
Const $NMERR_NO_NPP_SELECTED = 3018
Const $NMERR_NO_NPPS = 3016
Const $NMERR_NO_PROPERTY_DATABASE = 31
Const $NMERR_NO_PROTOCOLS_ENABLED = 42
Const $NMERR_NO_TRANSMITS_PENDING = 83
Const $NMERR_NO_VALID_NPP_DLLS = 3021
Const $NMERR_NOT_CAPTURING = 4
Const $NMERR_NOT_CONNECTED = 102
Const $NMERR_NOT_DELAYED = 106
Const $NMERR_NOT_ESP = 139
Const $NMERR_NOT_INITIALIZED = 135
Const $NMERR_NOT_LOCKED = 23
Const $NMERR_NOT_REALTIME = 108
Const $NMERR_NOT_STATS_ONLY = 110
Const $NMERR_NOT_SUPPORTED = 90
Const $NMERR_NOT_TRANSMIT = 112
Const $NMERR_ONE_MONITOR_PER_NETCARD = 2012
Const $NMERR_OUT_OF_DOS_MEMORY = 41
Const $NMERR_OUT_OF_MEMORY = 19
Const $NMERR_OUT_OF_RANGE = 24
Const $NMERR_PATH_NOT_FOUND = 84
Const $NMERR_PENDING = 73
Const $NMERR_PROMISCUOUS_MODE_NOT_SUPPORTED = 70
Const $NMERR_PROPERTY_NOT_FOUND = 32
Const $NMERR_PROTOCOL_ALREADY_ENABLED = 56
Const $NMERR_PROTOCOL_NOT_ENABLED = 34
Const $NMERR_PROTOCOL_NOT_FOUND = 35
Const $NMERR_PROTOCOL_NOT_REGISTERED = 79
Const $NMERR_REALTIME = 107
Const $NMERR_REG_OPERATION_FAILED = 120
Const $NMERR_REMOTE_NOT_A_SERVER = 126
Const $NMERR_REMOTE_VERSION_OUTOFSYNC = 127
Const $NMERR_ROUTING_INFO_NOT_PRESENT = 47
Const $NMERR_RPC_REMOTE_FAILURE = 1017
Const $NMERR_RUNAWAY_PROTOCOL = 72
Const $NMERR_SAVE_ALL_FAILED = 2019
Const $NMERR_SAVE_MONITOR_FAILED = 2029
Const $NMERR_SECURITY_BREACH_CAPTURE_DELETED = 123
Const $NMERR_SETTIMER_FAILED = 98
Const $NMERR_STACK_EMPTY = 15
Const $NMERR_STACK_OVERFLOW = 16
Const $NMERR_STATS_ONLY = 109
Const $NMERR_SUCCESS = 0
Const $NMERR_TIMEOUT = 96
Const $NMERR_TOO_MANY_PROTOCOLS = 17
Const $NMERR_TRANSMIT = 111
Const $NMERR_TRANSMIT_CANCELLED = 81
Const $NMERR_TRANSMIT_ERROR = 58
Const $NMERR_TRANSMITTING = 113
Const $NMERR_UNABLE_TO_CREATE_MONITOR = 2003
Const $NMERR_UNABLE_TO_GET_PROCADDR = 1014
Const $NMERR_UNABLE_TO_LOAD_LIBRARY = 1013
Const $NMERR_UNKNOWN_CAPTURETYPE = 101
Const $NMERR_UNKNOWN_CATEGORY = 1008
Const $NMERR_UNKNOWN_MACTYPE = 46
Const $NMERR_UNKNOWN_TAG = 1009
Const $NMERR_UNLOAD_PARSER_FAILED = 27
Const $NMERR_UPLEVEL_BLOB = 1002
Const $NMERR_UPLEVEL_CAPTURE_FILE = 117
Const $NMERR_WINDOWS_DRIVER_INIT_FAILURE = 64
Const $NMERR_WINDOWS_DRIVER_NOT_LOADED = 62
Const $NMERR_WINDOWS_ERROR = 85
Const $NMEVENTFLAG_DO_NOT_DISPLAY_DATE = 0x2000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_DESCRIPTION = 0x10000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_EVENT_NAME = 0x20000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_FIXED_COLUMNS = 0xFE000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_MACHINE = 0x8000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_SEVERITY = 0x80000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_SOURCE = 0x40000000
Const $NMEVENTFLAG_DO_NOT_DISPLAY_TIME = 0x4000000
Const $NMEVENTFLAG_EXPERT = 0x1
Const $NMEVENTFLAG_MONITOR = 0x0
Const $NMPWAIT_NOWAIT = 0x1
Const $NMPWAIT_USE_DEFAULT_WAIT = 0x0
Const $NMPWAIT_WAIT_FOREVER = 0xFFFF
Const $NNLEN = 80
Const $NNTP_MD_ID_BEGIN_RESERVED = 0xB000
Const $NNTP_MD_ID_END_RESERVED = 0xBFFF
Const $NO_ADDRESS = $WSANO_ADDRESS
Const $NO_ATTACHMENT = 0x0
Const $NO_DATA = $WSANO_DATA
Const $NO_ERR = 0
Const $NO_ERROR = 0
Const $NO_INDICES_LOADED = -15
Const $NO_INHERITANCE = 0x0
Const $NO_LONG_NAMES = 2
Const $NO_MORE_RESULTS = 2
Const $NO_MORE_ROWS = -2
Const $NO_MORE_RPC_RESULTS = 3
Const $NO_PERMISSION_REQUIRED = 0x1
Const $NO_PRIORITY = 0
Const $NO_PROPAGATE_INHERIT_ACE = 0x4
Const $NO_RECOVERY = $WSANO_RECOVERY
Const $NO_SCHEMA = ""
Const $NO_SUCH_CLASS = 0x4000F106
Const $NO_SUCH_EXCLUSION = 0x4000F107
Const $NO_SUCH_MODIFICATION = 0x4000F108
Const $NO_SUCH_RULES = 0x4000F109
Const $NO_SUCH_SYNTAX = 0x4000F10A
Const $NO_SUCH_TYPE = 0x4000F10B
Const $NO_SUCH_WORKSPACE = 0x4000F10C
Const $NO_TEXT_SCANNED = -11
Const $NO_TITLE = -1
Const $noAxis = 3
Const $NOBIND = -2
Const $NOCSSRVR = 1
Const $NODGNREC = 2
Const $NOERROR = 0
Const $NOMIRRORBITMAP = 0x80000000
Const $NON_STANDARD = 0x10000
Const $NON_VALIDATED_LOGON = 3
Const $NONANTIALIASED_QUALITY = 3
Const $NONAP = 8
Const $NONE_FLAGS = 0x80
Const $NONE_FLAGS_STR = ""
Const $nonfinalRev = 1
Const $NONOS = 5
Const $NONZEROLHND = $LMEM_MOVEABLE
Const $NONZEROLPTR = $LMEM_FIXED
Const $NOP_FUNCTION = 0
Const $NOPARITY = 0
Const $NORM_IGNORECASE = 0x1
Const $NORM_IGNOREKANATYPE = 0x40
Const $NORM_IGNORENONSPACE = 0x2
Const $NORM_IGNORESYMBOLS = 0x4
Const $NORM_IGNOREWIDTH = 0x8
Const $NORMAL_CACHE_ENTRY = 0x1
Const $NORMAL_MODE = 0x2
Const $NORMAL_PRIORITY_CLASS = 0x20
Const $NOT_AN_ENCODING = 0x4000F10D
Const $NOT_AN_ERROR = 0x80000
Const $NOT_AN_ERROR1 = 0x81600
Const $NOT_COMPRESSOR = -4
Const $NOT_CONCRETE = 0x4000F10E
Const $NOT_HILITER = -26
Const $NOT_INDEXER = -2
Const $NOT_PRESENT = 0x4000F10F
Const $NOT_PRIVATE = 0x4000F110
Const $NOT_SEARCHER = -3
Const $NOT_SUPPORTED = 0x8
Const $NOT_THE_SERVICES = 0x4000F111
Const $NOTIFIER_FLAG_NEW_THREAD = 0x1
Const $NOTIFIER_FLAG_ONE_SHOT = 0x2
Const $NOTIFIER_FLAG_SECONDS = 0x80000000
Const $NOTIFIER_TYPE_HANDLE_WAIT = 2
Const $NOTIFIER_TYPE_IMMEDIATE = 16
Const $NOTIFIER_TYPE_INTERVAL = 1
Const $NOTIFIER_TYPE_NOTIFY_EVENT = 4
Const $NOTIFIER_TYPE_STATE_CHANGE = 3
Const $NOTIFY_ABORT_DEFERRED = 0x40000000
Const $NOTIFY_BEGIN_INBOUND = 0x1
Const $NOTIFY_BEGIN_INBOUND_FLUSH = 0x4
Const $NOTIFY_BEGIN_OUTBOUND = 0x2
Const $NOTIFY_BEGIN_OUTBOUND_FLUSH = 0x8
Const $NOTIFY_CANCEL_MESSAGE = 0x80000000
Const $NOTIFY_CANCELED = 0x80000000
Const $NOTIFY_CLASS_DOMAIN_CHANGE = 3
Const $NOTIFY_CLASS_PACKAGE_CHANGE = 1
Const $NOTIFY_CLASS_ROLE_CHANGE = 2
Const $NOTIFY_CONFIG_CHANGE = 0x4000
Const $NOTIFY_CRITICAL_ERROR = 0x10000000
Const $NOTIFY_CRITSEC = 0x1000
Const $NOTIFY_END_INBOUND = 0x10000
Const $NOTIFY_END_INBOUND_FLUSH = 0x40000
Const $NOTIFY_END_OUTBOUND = 0x20000
Const $NOTIFY_END_OUTBOUND_FLUSH = 0x80000
Const $NOTIFY_NEWMAIL = 0x1
Const $NOTIFY_NEWMAIL_RECEIVED = 0x20000000
Const $NOTIFY_NONCRIT = 0x2000
Const $NOTIFY_READYTOSEND = 0x2
Const $NOTIFY_SENTDEFERRED = 0x4
Const $NOTIFY_SYNC = 0x40000000
Const $NOTIFYICON_VERSION = 3
Const $NOTLOGON = 6
Const $NOTSRCCOPY = 0x330008
Const $NOTSRCERASE = 0x1100A6
Const $NOUSRREC = 3
Const $NRC_ACTSES = 0xF
Const $NRC_BADDR = 0x7
Const $NRC_BRIDGE = 0x23
Const $NRC_BUFLEN = 0x1
Const $NRC_CANCEL = 0x26
Const $NRC_CANOCCR = 0x24
Const $NRC_CMDCAN = 0xB
Const $NRC_CMDTMO = 0x5
Const $NRC_DUPENV = 0x30
Const $NRC_DUPNAME = 0xD
Const $NRC_ENVNOTDEF = 0x34
Const $NRC_GOODRET = 0x0
Const $NRC_IFBUSY = 0x21
Const $NRC_ILLCMD = 0x3
Const $NRC_ILLNN = 0x13
Const $NRC_INCOMP = 0x6
Const $NRC_INUSE = 0x16
Const $NRC_INVADDRESS = 0x39
Const $NRC_INVDDID = 0x3B
Const $NRC_LOCKFAIL = 0x3C
Const $NRC_LOCTFUL = 0x11
Const $NRC_MAXAPPS = 0x36
Const $NRC_NAMCONF = 0x19
Const $NRC_NAMERR = 0x17
Const $NRC_NAMTFUL = 0xE
Const $NRC_NOCALL = 0x14
Const $NRC_NORES = 0x9
Const $NRC_NORESOURCES = 0x38
Const $NRC_NOSAPS = 0x37
Const $NRC_NOWILD = 0x15
Const $NRC_OPENERR = 0x3F
Const $NRC_OSRESNOTAV = 0x35
Const $NRC_PENDING = 0xFF
Const $NRC_REMTFUL = 0x12
Const $NRC_SABORT = 0x18
Const $NRC_SCLOSED = 0xA
Const $NRC_SNUMOUT = 0x8
Const $NRC_SYSTEM = 0x40
Const $NRC_TOOMANY = 0x22
Const $NS_ALL = 0
Const $NS_DEFAULT = 0
Const $NS_DHCP = 6
Const $NS_DNS = 12
Const $NS_EVENT_FROM_N = 0x4
Const $NS_EVENT_FROM_START = 0x8
Const $NS_EVENT_LAST_N = 0x1
Const $NS_EVENT_LAST_SECS = 0x2
Const $NS_EVENT_LOOP = 0x10000
Const $NS_GET_EVENT_IDS_FN_NAME = "GetEventIds"
Const $NS_MS = 30
Const $NS_NBP = 20
Const $NS_NDS = 2
Const $NS_NETBT = 13
Const $NS_NETDES = 60
Const $NS_NIS = 41
Const $NS_NISPLUS = 42
Const $NS_NTDS = 32
Const $NS_PEER_BROWSE = 3
Const $NS_REQ_ALLOW_MULTIPLE = 0x2
Const $NS_REQ_ONE = 1
Const $NS_REQ_ONE_OR_MORE = 3
Const $NS_REQ_PRESENT = 0x1
Const $NS_REQ_ZERO = 0
Const $NS_REQ_ZERO_OR_MORE = 2
Const $NS_SAP = 1
Const $NS_SLP = 5
Const $NS_STDA = 31
Const $NS_TCPIP_HOSTS = 11
Const $NS_TCPIP_LOCAL = 10
Const $NS_VNS = 50
Const $NS_WINS = 14
Const $NS_WRQ = 50
Const $NS_X500 = 40
Const $NSPROTO_IPX = 1000
Const $NSPROTO_SPX = 1256
Const $NSPROTO_SPXII = 1257
Const $NSS_CONTROL_ISNSSFILE = 4
Const $NSS_CONTROL_MARK = 1
Const $NSS_CONTROL_UNMARK = 2
Const $NSTYPE_DYNAMIC = 0x2
Const $NSTYPE_ENUMERABLE = 0x4
Const $NSTYPE_HIERARCHICAL = 0x1
Const $NSTYPE_WORKGROUP = 0x8
Const $NT_CONSOLE_PROPS_SIG = 0xA0000002
Const $NT_FE_CONSOLE_PROPS_SIG = 0xA0000004
Const $NT351_INTERFACE_SIZE = 0x40
Const $NT4_MAJOR_VERSION = 1
Const $NT4SP4_MAJOR_VERSION = 2
Const $NT5_MAJOR_VERSION = 3
Const $NT51_MAJOR_VERSION = 4
Const $NTBSTRINGBIND = 11
Const $NTE_BAD_ALGID = 0x80090008
Const $NTE_BAD_DATA = 0x80090005
Const $NTE_BAD_FLAGS = 0x80090009
Const $NTE_BAD_HASH = 0x80090002
Const $NTE_BAD_HASH_STATE = 0x8009000C
Const $NTE_BAD_KEY = 0x80090003
Const $NTE_BAD_KEY_STATE = 0x8009000B
Const $NTE_BAD_KEYSET = 0x80090016
Const $NTE_BAD_KEYSET_PARAM = 0x8009001F
Const $NTE_BAD_LEN = 0x80090004
Const $NTE_BAD_PROV_TYPE = 0x80090014
Const $NTE_BAD_PROVIDER = 0x80090013
Const $NTE_BAD_PUBLIC_KEY = 0x80090015
Const $NTE_BAD_SIGNATURE = 0x80090006
Const $NTE_BAD_TYPE = 0x8009000A
Const $NTE_BAD_UID = 0x80090001
Const $NTE_BAD_VER = 0x80090007
Const $NTE_DOUBLE_ENCRYPT = 0x80090012
Const $NTE_EXISTS = 0x8009000F
Const $NTE_FAIL = 0x80090020
Const $NTE_FIXEDPARAMETER = 0x80090025
Const $NTE_KEYSET_ENTRY_BAD = 0x8009001A
Const $NTE_KEYSET_NOT_DEF = 0x80090019
Const $NTE_NO_KEY = 0x8009000D
Const $NTE_NO_MEMORY = 0x8009000E
Const $NTE_NOT_FOUND = 0x80090011
Const $NTE_OP_OK = 0
Const $NTE_PERM = 0x80090010
Const $NTE_PROV_DLL_NOT_FOUND = 0x8009001E
Const $NTE_PROV_TYPE_ENTRY_BAD = 0x80090018
Const $NTE_PROV_TYPE_NO_MATCH = 0x8009001B
Const $NTE_PROV_TYPE_NOT_DEF = 0x80090017
Const $NTE_PROVIDER_DLL_FAIL = 0x8009001D
Const $NTE_SIGNATURE_FILE_BAD = 0x8009001C
Const $NTE_SILENT_CONTEXT = 0x80090022
Const $NTE_SYS_ERR = 0x80090021
Const $NTE_TEMPORARY_PROFILE = 0x80090024
Const $NTE_TOKEN_KEYSET_STORAGE_FULL = 0x80090023
Const $NTEXP_ENTRY_COUNT = 5
Const $NTEXPMSG_PROGRESS_TITLE = 0x11
Const $NTEXPORT_CANCELLED = 0x8000002D
Const $NTEXPORT_CANCELLED_NOFILE = 0x8000002E
Const $NTEXPORT_COMPLETE = 0x4000002B
Const $NTEXPORT_COMPLETE_NOFILE = 0x4000002C
Const $NTEXPORT_DC_NOT_FOUND = 0xC000012F
Const $NTEXPORT_SERVER_NOT_FOUND = 0xC0000131
Const $NTEXPORT_STARTED = 0x4000002A
Const $NTEXPORT_STARTED_NOFILE = 0x4000002F
Const $NTEXPORT_USER_ENUM_ERROR = 0xC0000130
Const $NTLMSP_NAME = "NTLM"
Const $NTLMSP_NAME_A = "NTLM"
Const $NTM_BOLD = 0x20
Const $NTM_DSIG = 0x200000
Const $NTM_ITALIC = 0x1
Const $NTM_MULTIPLEMASTER = 0x80000
Const $NTM_NONNEGATIVE_AC = 0x10000
Const $NTM_PS_OPENTYPE = 0x20000
Const $NTM_REGULAR = 0x40
Const $NTM_TT_OPENTYPE = 0x40000
Const $NTM_TYPE1 = 0x100000
Const $NTMS_APPLICATIONNAME_LENGTH = 64
Const $NTMS_BARCODE_LENGTH = 64
Const $NTMS_COMPUTERNAME_LENGTH = 64
Const $NTMS_DESCRIPTION_LENGTH = 127
Const $NTMS_DEVICENAME_LENGTH = 64
Const $NTMS_I1_MESSAGE_LENGTH = 127
Const $NTMS_MAXATTR_LENGTH = 0x10000
Const $NTMS_MAXATTR_NAMELEN = 32
Const $NTMS_MESSAGE_LENGTH = 256
Const $NTMS_OBJECTNAME_LENGTH = 64
Const $NTMS_OMID_TYPE_FILESYSTEM_INFO = 0x2
Const $NTMS_OMID_TYPE_RAW_LABEL = 0x1
Const $NTMS_OMIDLABELID_LENGTH = 255
Const $NTMS_OMIDLABELINFO_LENGTH = 256
Const $NTMS_OMIDLABELTYPE_LENGTH = 64
Const $NTMS_POOLHIERARCHY_LENGTH = 512
Const $NTMS_PRODUCTNAME_LENGTH = 128
Const $NTMS_REVISION_LENGTH = 32
Const $NTMS_SEQUENCE_LENGTH = 32
Const $NTMS_SERIALNUMBER_LENGTH = 32
Const $NTMS_USERNAME_LENGTH = 64
Const $NTMS_VENDORNAME_LENGTH = 128
Const $NTMSMLI_MAXAPPDESCR = 256
Const $NTMSMLI_MAXIDSIZE = 256
Const $NTMSMLI_MAXTYPE = 64
Const $NTSEC_ERROR_ACCOUNT_DISABLED = 0xE90005F4
Const $NTSEC_ERROR_ACCOUNT_LOCKED = 0xE90005F5
Const $NTSEC_ERROR_INVALID_NEW_PASSWORD = 0xE90005E7
Const $NTSEC_ERROR_INVALID_OLD_PASSWORD = 0xE90005E4
Const $NTSEC_ERROR_INVALID_USERNAME = 0xE90005E3
Const $NTSEC_ERROR_NEW_PASSWORD_BAD_CHAR = 0xE90005EB
Const $NTSEC_ERROR_NEW_PASSWORD_HAS_REPEATING_CHARS = 0xE90005E8
Const $NTSEC_ERROR_NEW_PASSWORD_HISTORY_CONFLICT = 0xE90005F1
Const $NTSEC_ERROR_NEW_PASSWORD_NON_ALPHANUMERIC = 0xE90005EE
Const $NTSEC_ERROR_NEW_PASSWORD_NOT_ALLOWED = 0xE90005F0
Const $NTSEC_ERROR_NEW_PASSWORD_NULL = 0xE90005ED
Const $NTSEC_ERROR_NEW_PASSWORD_SAME_AS_PREVIOUS = 0xE90005EF
Const $NTSEC_ERROR_NEW_PASSWORD_SPACES = 0xE90005EC
Const $NTSEC_ERROR_NEW_PASSWORD_TOO_LONG = 0xE90005E9
Const $NTSEC_ERROR_NEW_PASSWORD_TOO_SHORT = 0xE90005EA
Const $NTSEC_ERROR_NOT_IMPLEMENTED = 0xE90005E5
Const $NTSEC_ERROR_PASSWORD_EXPIRED = 0xE90005F3
Const $NTSEC_ERROR_REMOTE_UNREACHABLE = 0xE90005E2
Const $NTSEC_ERROR_REQUEST_REJECTED = 0xE90005F2
Const $NTSEC_ERROR_UNABLE_TO_PROCESS_REQUEST = 0xE90005E1
Const $NTSEC_ERROR_USER_CANNOT_CHANGE_PASSWORD = 0xE90005F6
Const $NULL = 0
Const $NULL_BRUSH = 5
Const $NULL_FIELD_NAME = 0x6
Const $NULL_PEN = 8
Const $NULL_QOS_TYPE = 0xFFFFFFFD
Const $NULL_SYM_DUMP_PARAM = 0x5
Const $NULL_USERSETINFO_PASSWD = " "
Const $NULLREGION = 1
Const $NUM_ALERTABLE_THREADS = 2
Const $NUM_BASIC_COLORS = 48
Const $NUM_CUSTOM_COLORS = 16
Const $NUM_EISA_RANGES = 4
Const $NUM_RESOURCE_MAP = 256
Const $NUM_SERVICETYPES = 8
Const $NUMALLOCENTRIES = 10
Const $NUMBER_OF_EXPORTED_VARIABLES = $ROUTE_STATE + 1
Const $NUMBRUSHES = 16
Const $NUMCOLORS = 24
Const $NUMERICBIND = 18
Const $NUMFONTS = 22
Const $NUMLOCK_ON = 0x20
Const $NUMMARKERS = 20
Const $NUMPENS = 18
Const $NUMPRS_CURRENCY = 0x400
Const $NUMPRS_DECIMAL = 0x100
Const $NUMPRS_EXPONENT = 0x800
Const $NUMPRS_HEX_OCT = 0x40
Const $NUMPRS_INEXACT = 0x20000
Const $NUMPRS_LEADING_MINUS = 0x10
Const $NUMPRS_LEADING_PLUS = 0x4
Const $NUMPRS_LEADING_WHITE = 0x1
Const $NUMPRS_NEG = 0x10000
Const $NUMPRS_PARENS = 0x80
Const $NUMPRS_STD = 0x1FFF
Const $NUMPRS_THOUSANDS = 0x200
Const $NUMPRS_TRAILING_MINUS = 0x20
Const $NUMPRS_TRAILING_PLUS = 0x8
Const $NUMPRS_TRAILING_WHITE = 0x2
Const $NUMPRS_USE_ALL = 0x1000
Const $NUMRESERVED = 106
Const $NWEXP_ENTRY_COUNT = 4
Const $NWEXPMSG_PROGRESS_TITLE = 0x12
Const $NWEXPORT_ATTACH_FAILED = 0xC0000135
Const $NWEXPORT_CANCELLED = 0x80000033
Const $NWEXPORT_CANCELLED_NOFILE = 0x80000034
Const $NWEXPORT_COMPLETE = 0x40000031
Const $NWEXPORT_COMPLETE_NOFILE = 0x40000032
Const $NWEXPORT_DETACHED_FAILED = 0xC0000137
Const $NWEXPORT_LOGIN_FAILED = 0xC0000134
Const $NWEXPORT_LOGOUT_FAILED = 0xC0000136
Const $NWEXPORT_NO_USER = 0xC0000138
Const $NWEXPORT_NWDLL_LOAD_FAILED = 0xC0000133
Const $NWEXPORT_STARTED = 0x40000030
Const $NWEXPORT_STARTED_NOFILE = 0x40000035
Const $NWSAP_DISPLAY_NAME = "NW Sap Agent"